<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<p id="social">
<a href="http://fr-fr.facebook.com/pages/" target="_blank"><img src="/images/theme/social/facebook.png" alt="Facebook" /></a>
<a href="http://www.twitter.com/#!/" target="_blank"><img src="/images/theme/social/twitter.png" alt="Twitter"/></a>
<a href="/fr/rss" target="_blank"><img src="/images/theme/social/rss.png" alt="RSS" /></a>
</p>
<script type="text/javascript">
$('#social img').hover(function() { $(this).animate({'opacity' : '0.5'}, 200); }, function() { $(this).animate({'opacity' : '1.0'}, 200); } );
</script>
<p>Votre site <b>iZend</b> est maintenant opérationnel.</p>
<p class="readmore">Lisez la <a href="<?php echo $base_path; ?>/fr/documentation">documentation</a>.</p>
