<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<input id="content_create" name="content_create" type="submit" value="Ajouter" />
un type
<?php
$selected=$new_content_type ? $new_content_type : 'text';
?>
<select id="content_new_type" name="content_new_type" size="1">
<option value="text" <?php echo $selected == 'text' ? 'selected="selected"' : ''; ?>>Texte</option>
<option value="infile" <?php echo $selected == 'infile' ? 'selected="selected"' : ''; ?>>Insertion</option>
<option value="download" <?php echo $selected == 'download' ? 'selected="selected"' : ''; ?>>Téléchargement</option>
<option value="file" <?php echo $selected == 'file' ? 'selected="selected"' : ''; ?>>Fichier</option>
<option value="longtail" <?php echo $selected == 'longtail' ? 'selected="selected"' : ''; ?>>LongTail</option>
</select>
#
<input id="content_new_number" name="content_new_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($new_content_number, ENT_COMPAT, 'UTF-8'); ?>" title="Numéro"/>
<?php if ($node_contents): ?>
ou
<input id="content_delete" name="content_delete" type="submit" value="Supprimer" />
le #
<input id="content_old_number" name="content_old_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($old_content_number, ENT_COMPAT, 'UTF-8'); ?>" title="Numéro"/>
<?php endif; ?>
</p>
<?php if ($node_contents): ?>
<?php
$i=1;
foreach ($node_contents as $c) {
	$content_ignored=false;
	$content_text='';
	$content_eval=false;
	$content_file=$content_format=$content_lineno=false;
	$content_start=$content_end=0;
	$content_download=$content_path=false;
	$content_infile=false;
	$content_longtail_file=$content_longtail_image=false;
	$content_longtail_width=$content_longtail_height=0;
	$content_longtail_skin=false;
	$content_longtail_icons=false;
	$content_longtail_duration=0;
	$content_longtail_autostart=$content_longtail_repeat=false;
	extract($c);	/* content_id content_number content_ignored content_type (content_text | content_file content_start content_end content_format content_lineno | content_download content_path | content_infile |content_longtail_file content_longtail_image content_longtail_width content_longtail_height content_longtail_skin content_longtail_icons content_longtail_duration content_longtail_autostart content_longtail_repeat) content_pos */
?>
<p class="<?php echo $content_ignored ? 'ignored' : (($i % 2) ? 'odd' : 'even'); ?>">
<input name="content_id[<?php echo $i; ?>]" type="hidden" value="<?php echo $content_id; ?>"/>
<input name="content_p[<?php echo $i; ?>]" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($content_pos, ENT_COMPAT, 'UTF-8'); ?>"/>
<input name="content_ignored[<?php echo $i; ?>]" type="checkbox" <?php if ($content_ignored) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/cross.png" alt="ignoré" title="Ignoré" />
<?php switch ($content_type): ?>
<?php case 'text': ?>
<label>Texte :</label>
<?php break; ?>
<?php case 'file': ?>
<label>Fichier :</label>
<?php break; ?>
<?php case 'download': ?>
<label>Téléchargement :</label>
<?php break; ?>
<?php case 'infile': ?>
<label>Insertion :</label>
<?php break; ?>
<?php case 'longtail': ?>
<label>LongTail :</label>
<?php break; ?>
<?php endswitch; ?>
</p>
<?php switch ($content_type): ?>
<?php case 'text': ?>
<div class="tagbar">
<img src="<?php echo $base_path; ?>/images/theme/edit/p.png" alt="&lt;p&gt;" title="p" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;p&gt;','&lt;/p&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/b.png" alt="&lt;b&gt;" title="b" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;b&gt;','&lt;/b&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/i.png" alt="&lt;i&gt;" title="i" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;i&gt;','&lt;/i&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/u.png" alt="&lt;u&gt;" title="u" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;u&gt;','&lt;/u&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/s.png" alt="&lt;s&gt;" title="s" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;s&gt;','&lt;/s&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/h4.png" alt="&lt;h4&gt;" title="h4" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;h4&gt;','&lt;/h4&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/h5.png" alt="&lt;h5&gt;" title="h5" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;h5&gt;','&lt;/h5&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/h6.png" alt="&lt;h6&gt;" title="h6" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;h6&gt;','&lt;/h6&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/ol.png" alt="&lt;ol&gt;" title="ol" onclick="addtag('content_text_<?php echo $i; ?>', '','\n&lt;ol&gt;\n&lt;li&gt;&lt;/li&gt;\n&lt;/ol&gt;\n')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/ul.png" alt="&lt;ul&gt;" title="ul" onclick="addtag('content_text_<?php echo $i; ?>', '','\n&lt;ul&gt;\n&lt;li&gt;&lt;/li&gt;\n&lt;/ul&gt;\n')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/fixed.png" alt="&lt;code&gt;" title="code" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;code&gt;','&lt;/code&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/shell.png" alt="&lt;pre&gt;&lt;code&gt;" title="pre code" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;pre>&lt;code&gt;','&lt;/code>&lt;/pre&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/quote.png" alt="&lt;blockquote&gt;" title="blockquote" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;blockquote&gt;','&lt;/blockquote&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/img.png" alt="&lt;img&gt;" title="img" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;img src=\x22','\x22 alt=\x22\x22 title=\x22\x22 /&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/world.png" alt="&lt;a&gt;" title="a" onclick="addtag('content_text_<?php echo $i; ?>', '&lt;a href=\x22#\x22&gt;','&lt;/a&gt;')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/entquote.png" alt="entquote" title="entquote" onclick="entquote('content_text_<?php echo $i; ?>')"/>
<span><input name="content_eval[<?php echo $i; ?>]" type="checkbox" <?php if ($content_eval) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/code.png" alt="PHP" title="seval" /></span>
</div>
<textarea id="content_text_<?php echo $i; ?>" name="content_text[<?php echo $i; ?>]" cols="100" rows="8"><?php echo htmlspecialchars($content_text, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" />
<?php break; ?>
<?php case 'file': ?>
<p>
<input name="content_file[<?php echo $i; ?>]" type="text" size="40" maxlength="200" value="<?php echo htmlspecialchars($content_file, ENT_COMPAT, 'UTF-8'); ?>" title="Fichier" />
<input name="content_start[<?php echo $i; ?>]" type="text" size="5" maxlength="5" value="<?php echo htmlspecialchars($content_start, ENT_COMPAT, 'UTF-8'); ?>" title="Début" />
<input name="content_end[<?php echo $i; ?>]" type="text" size="5" maxlength="5" value="<?php echo htmlspecialchars($content_end, ENT_COMPAT, 'UTF-8'); ?>" title="Fin" />
<input name="content_format[<?php echo $i; ?>]" type="text" size="10" maxlength="20" value="<?php echo htmlspecialchars($content_format, ENT_COMPAT, 'UTF-8'); ?>" title="Format" />
<input name="content_lineno[<?php echo $i; ?>]" type="checkbox" <?php if ($content_lineno) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/ol.png" alt="numéroter" title="Numéroter" />
</p>
<?php break; ?>
<?php case 'download': ?>
<p>
<input name="content_download[<?php echo $i; ?>]" type="text" size="20" maxlength="50" value="<?php echo htmlspecialchars($content_download, ENT_COMPAT, 'UTF-8'); ?>" title="Nom" />
<input name="content_path[<?php echo $i; ?>]" type="text" size="40" maxlength="200" value="<?php echo htmlspecialchars($content_path, ENT_COMPAT, 'UTF-8'); ?>" title="Fichier" />
</p>
<?php break; ?>
<?php case 'infile': ?>
<p>
<input name="content_infile[<?php echo $i; ?>]" type="text" size="40" maxlength="200" value="<?php echo htmlspecialchars($content_infile, ENT_COMPAT, 'UTF-8'); ?>" title="Fichier" />
</p>
<?php break; ?>
<?php case 'longtail': ?>
<p>
<input name="content_longtail_file[<?php echo $i; ?>]" type="text" size="40" maxlength="200" value="<?php echo htmlspecialchars($content_longtail_file, ENT_COMPAT, 'UTF-8'); ?>" title="Fichier" />
<input name="content_longtail_width[<?php echo $i; ?>]" type="text" size="5" maxlength="5" value="<?php echo htmlspecialchars($content_longtail_width, ENT_COMPAT, 'UTF-8'); ?>" title="Largeur" />
x
<input name="content_longtail_height[<?php echo $i; ?>]" type="text" size="5" maxlength="5" value="<?php echo htmlspecialchars($content_longtail_height, ENT_COMPAT, 'UTF-8'); ?>" title="Hauteur" />
<img src="<?php echo $base_path; ?>/images/theme/edit/time.png" alt="Durée : " />
<input name="content_longtail_duration[<?php echo $i; ?>]" type="text" size="5" maxlength="5" value="<?php echo htmlspecialchars($content_longtail_duration, ENT_COMPAT, 'UTF-8'); ?>" title="Durée" />
<input name="content_longtail_autostart[<?php echo $i; ?>]" type="checkbox" <?php if ($content_longtail_autostart) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/play.png" alt="auto" title="Auto" /><input name="content_longtail_repeat[<?php echo $i; ?>]" type="checkbox" <?php if ($content_longtail_repeat) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/repeat.png" alt="boucle" title="Boucle" />
</p>
<p>
<input name="content_longtail_image[<?php echo $i; ?>]" type="text" size="40" maxlength="200" value="<?php echo htmlspecialchars($content_longtail_image, ENT_COMPAT, 'UTF-8'); ?>" title="Image" />
<input name="content_longtail_icons[<?php echo $i; ?>]" type="checkbox" <?php if ($content_longtail_icons) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/imgplay.png" alt="icônes" title="Contrôles" />
</p>
<p>
<input name="content_longtail_skin[<?php echo $i; ?>]" type="text" size="40" maxlength="200" value="<?php echo htmlspecialchars($content_longtail_skin, ENT_COMPAT, 'UTF-8'); ?>" title="Habillage" />
</p>
<?php break; ?>
<?php endswitch; ?>
<?php
	$i++;
}
?>
<p>
<input id="content_modify" name="content_modify" type="submit" value="Modifier" />
le contenu
</p>
<?php endif; ?>
</form>
<?php
$focus=false;
if ($bad_new_content_number) {
	 $focus='#content_new_number';
}
else if ($missing_old_content_number or $bad_old_content_number) {
	 $focus='#content_old_number';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
<script type="text/javascript">
$(document).ready(function() {
	$('.grippie').each(function() {
		var grippie = $(this);
		var textarea = grippie.prev().prev();
		var offset;

		grippie.mousedown(startDrag);

	    function startDrag(e) {
	      offset = textarea.height() - e.pageY;
	      textarea.css('opacity', 0.25);
	      $(document).mousemove(performDrag).mouseup(endDrag);
	      return false;
	    }

	    function performDrag(e) {
	      textarea.height(Math.max(32, offset + e.pageY) + 'px');
	      return false;
	    }

	    function endDrag(e) {
	      $(document).unbind('mousemove', performDrag).unbind('mouseup', endDrag);
	      textarea.css('opacity', 1);
	    }
	});
});
</script>
