<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    24
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<h3<?php if ($thread_title): ?> title="<?php echo $thread_id; ?>"<?php endif; ?>><?php echo htmlspecialchars($thread_title ? $thread_title : $thread_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php echo $inlanguages; ?>
</p>
<p>
<input id="thread_title" name="thread_title" type="text" size="40" maxlength="100" value="<?php echo htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8'); ?>" title="Titre" onkeypress="return submitonenter(event, 'thread_edit')"/>
<label>URL :</label>
<input id="thread_name" name="thread_name" type="text" size="40" maxlength="100" value="<?php echo $thread_name; ?>" onkeypress="return submitonenter(event, 'thread_edit')"/>
</p>
<p><label>Extrait :</label></p>
<p>
<textarea name="thread_abstract" cols="80" rows="5"><?php echo htmlspecialchars($thread_abstract, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><span class="grippie btn_edit btn_grippie">===</span>
</p>
<p><label>Nuage :</label></p>
<p>
<textarea name="thread_cloud" cols="80" rows="5"><?php echo htmlspecialchars($thread_cloud, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><span class="grippie btn_edit btn_grippie">===</span>
</p>
<p>
<label>Type :</label>
<select name="thread_type" size="1">
<option value="thread"<?php if ($thread_type == 'thread'): ?> selected="selected"<?php endif; ?>>Fil</option>
<?php foreach ($supported_threads as $type): ?>
<?php if ($type == 'folder'): ?>
<option value="folder"<?php if ($thread_type == 'folder'): ?> selected="selected"<?php endif; ?>>Dossier</option>
<?php elseif ($type == 'story'): ?>
<option value="story"<?php if ($thread_type == 'story'): ?> selected="selected"<?php endif; ?>>Article</option>
<?php elseif ($type == 'book'): ?>
<option value="book"<?php if ($thread_type == 'book'): ?> selected="selected"<?php endif; ?>>Manuel</option>
<?php elseif ($type == 'rss'): ?>
<option value="rss"<?php if ($thread_type == 'rss'): ?> selected="selected"<?php endif; ?>>RSS</option>
<?php elseif ($type == 'newsletter'): ?>
<option value="newsletter"<?php if ($thread_type == 'newsletter'): ?> selected="selected"<?php endif; ?>>Infolettre</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
</p>
<fieldset id="thread_options">
<legend>Options</legend>
<input id="thread_search" name="thread_search" type="checkbox"<?php if ($thread_search): ?> checked="checked"<?php endif; ?> /><label for="thread_search"><span class="btn_edit btn_search">recherche</span></label>
<input id="thread_tag" name="thread_tag" type="checkbox"<?php if ($thread_tag): ?> checked="checked"<?php endif; ?> /><label for="thread_tag"><span class="btn_edit btn_tag">nuage</span></label>
<input id="thread_comment" name="thread_comment" type="checkbox"<?php if ($thread_comment): ?> checked="checked"<?php endif; ?> /><label for="thread_comment"><span class="btn_edit btn_comment">commenter</span></label>
<input id="thread_morecomment" name="thread_morecomment" type="checkbox"<?php if ($thread_morecomment): ?> checked="checked"<?php endif; ?> /><label for="thread_morecomment"><span class="btn_edit btn_morecomment">commenter+</span></label>
<input id="thread_vote" name="thread_vote" type="checkbox"<?php if ($thread_vote): ?> checked="checked"<?php endif; ?> /><label for="thread_vote"><span class="btn_edit btn_vote">voter</span></label>
<input id="thread_morevote" name="thread_morevote" type="checkbox"<?php if ($thread_morevote): ?> checked="checked"<?php endif; ?> /><label for="thread_morevote"><span class="btn_edit btn_morevote">voter+</span></label>
<input id="thread_ilike" name="thread_ilike" type="checkbox"<?php if ($thread_ilike): ?> checked="checked"<?php endif; ?> /><label for="thread_ilike"><span class="btn_edit btn_ilike">facebook</span></label>
<input id="thread_tweet" name="thread_tweet" type="checkbox"<?php if ($thread_tweet): ?> checked="checked"<?php endif; ?> /><label for="thread_tweet"><span class="btn_edit btn_tweet">twitter</span></label>
<input id="thread_plusone" name="thread_plusone" type="checkbox"<?php if ($thread_plusone): ?> checked="checked"<?php endif; ?> /><label for="thread_plusone"><span class="btn_edit btn_plusone">google+</span></label>
<input id="thread_linkedin" name="thread_linkedin" type="checkbox"<?php if ($thread_linkedin): ?> checked="checked"<?php endif; ?> /><label for="thread_linkedin"><span class="btn_edit btn_linkedin">linkedin</span></label>
</fieldset>
<p>
<input class="submit submit_edit" id="thread_edit" name="thread_edit" type="submit" value="Éditer" />
</p>
<script type="text/javascript">
$(document).ready(function() {
	$('.grippie').each(function() {
		var grippie = $(this);
		var textarea = grippie.prev().prev();
		var offset;

		grippie.mousedown(startDrag);

	    function startDrag(e) {
	      offset = textarea.height() - e.pageY;
	      textarea.css('opacity', 0.25);
	      $(document).mousemove(performDrag).mouseup(endDrag);
	      return false;
	    }

	    function performDrag(e) {
	      textarea.height(Math.max(32, offset + e.pageY) + 'px');
	      return false;
	    }

	    function endDrag(e) {
	      $(document).unbind('mousemove', performDrag).unbind('mouseup', endDrag);
	      textarea.css('opacity', 1);
	    }
	});
});
</script>
<h4>Contenu</h4>
<p>
<input class="submit submit_add" id="node_create" name="node_create" type="submit" value="Ajouter" />
le contenu
<input id="new_node_title" name="new_node_title" type="text" size="50" maxlength="100" value="<?php echo htmlspecialchars($new_node_title, ENT_COMPAT, 'UTF-8'); ?>" title="Titre" onkeypress="return focusonenter(event, 'new_node_number')"/>
<span class="nowrap">
#
<input id="new_node_number" name="new_node_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($new_node_number, ENT_COMPAT, 'UTF-8'); ?>" title="Numéro" onkeypress="return submitonenter(event, 'node_create')"/>
</span>
</p>
<?php if ($thread_contents): ?>
<fieldset class="block">
<legend>Sommaire</legend>
<table cellpadding="2" cellspacing="0">
<tbody>
<?php
$i=1;
$maxlen=strlen(count($thread_contents))+1;
foreach ($thread_contents as $c) {
	extract($c);	/* pos, node_id, node_title, node_url, node_number, node_ignored */
	$node_url .= '?' . 'clang=' . $clang;
?>
<tr>
<td><input name="p[<?php echo $i; ?>]" type="text" size="2" maxlength="<?php echo $maxlen; ?>" value="<?php echo $pos; ?>" /></td>
<td><a href="<?php echo $node_url; ?>" title="<?php echo $node_id; ?>"><?php echo $node_title ? htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8') : $node_id; ?></a></td>
<?php if ($node_ignored): ?>
<td><span class="btn_edit btn_ignored">X</span></td>
<?php endif; ?>
</tr>
<?php
	$i++;
}
?>
</tbody>
</table>
</fieldset>
<p>
<input class="submit submit_sort" id="thread_reorder" name="thread_reorder" type="submit" value="Trier" />
le fil ou
<input class="submit submit_hide" id="node_hide" name="node_hide" type="submit" value="Cacher" />
ou
<input class="submit submit_show" id="node_show" name="node_show" type="submit" value="Montrer" />
ou
<input class="submit submit_delete" id="node_delete" name="node_delete" type="submit" value="Supprimer" />
le contenu
<span class="nowrap">
#
<input id="old_node_number" name="old_node_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($old_node_number, ENT_COMPAT, 'UTF-8'); ?>" title="Numéro" onkeypress="return submitonenter(event, 'node_delete')"/>
</span>
<?php if ($confirm_delete_node): ?>
<input class="submit submit_confirm" id="node_confirmdelete" name="node_confirmdelete" type="submit" value="Confirmer" />
<?php endif; ?>
</p>
<?php endif; ?>
</form>
<?php
$focus=false;
if ($missing_thread_name or $bad_thread_name) {
	$focus='#thread_name';
}
else if ($missing_new_node_title or $bad_new_node_title) {
	$focus='#new_node_title';
}
else if ($bad_new_node_number) {
	$focus='#new_node_number';
}
else if ($missing_old_node_number or $bad_old_node_number) {
	$focus='#old_node_number';
}
else if ($confirm_delete_node) {
	$focus='#old_node_number';
}
?>
<?php if ($focus): ?>
<?php head('javascript', 'jquery.scrollTo', 'screen'); ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus(); $.scrollTo('<?php echo $focus; ?>', {offset: -200}); });
</script>
<?php endif; ?>
