<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    14
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<h3><?php echo htmlspecialchars($site_title ? $site_title : $sitename, ENT_COMPAT, 'UTF-8'); ?></h3>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php echo $inlanguages; ?>
</p>
<p>
<input class="submit submit_add" id="thread_create" name="thread_create" type="submit" value="Ajouter" />
le fil
<input id="new_thread_title" name="new_thread_title" type="text" size="40" maxlength="100" value="<?php echo htmlspecialchars($new_thread_title, ENT_COMPAT, 'UTF-8'); ?>" title="Titre" onkeypress="return focusonenter(event, 'new_thread_number')"/>
#
<input id="new_thread_number" name="new_thread_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($new_thread_number, ENT_COMPAT, 'UTF-8'); ?>" title="Numéro" onkeypress="return submitonenter(event, 'thread_create')"/>
type
<select name="new_thread_type" size="1">
<option value="thread"<?php if ($new_thread_type == 'thread'): ?> selected="selected"<?php endif; ?>>Fil</option>
<?php foreach ($supported_threads as $type): ?>
<?php if ($type == 'folder'): ?>
<option value="folder"<?php if ($new_thread_type == 'folder'): ?> selected="selected"<?php endif; ?>>Dossier</option>
<?php elseif ($type == 'story'): ?>
<option value="story"<?php if ($new_thread_type == 'story'): ?> selected="selected"<?php endif; ?>>Article</option>
<?php elseif ($type == 'book'): ?>
<option value="book"<?php if ($new_thread_type == 'book'): ?> selected="selected"<?php endif; ?>>Manuel</option>
<?php elseif ($type == 'rss'): ?>
<option value="rss"<?php if ($new_thread_type == 'rss'): ?> selected="selected"<?php endif; ?>>RSS</option>
<?php elseif ($type == 'newsletter'): ?>
<option value="newsletter"<?php if ($new_thread_type == 'newsletter'): ?> selected="selected"<?php endif; ?>>Infolettre</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
</p>
<?php if ($thread_list): ?>
<fieldset class="block">
<legend>Catalogue</legend>
<table cellpadding="2" cellspacing="0">
<tbody>
<?php
$i=1;
foreach ($thread_list as $tr) {
	extract($tr);	/* pos, thread_id, thread_title, thread_number, thread_url */
	$thread_url .= '?' . 'clang=' . $clang;
?>
<tr>
<td><input name="p[<?php echo $i; ?>]" type="text" size="2" maxlength="3" value="<?php echo $pos; ?>" /></td>
<td class="aright"><a href="<?php echo $thread_url; ?>"><?php echo $thread_id; ?></a></td>
<?php if ($thread_title): ?>
<td><a href="<?php echo $thread_url; ?>"><?php echo htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8'); ?></a></td>
<?php endif; ?>
</tr>
<?php
	$i++;
}
?>
</tbody>
</table>
</fieldset>
<p>
<input class="submit submit_sort" id="threadlist_reorder" name="threadlist_reorder" type="submit" value="Trier" />
le contenu ou
<input class="submit submit_delete" id="thread_delete" name="thread_delete" type="submit" value="Supprimer" />
le fil #
<input id="old_thread_number" name="old_thread_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($old_thread_number, ENT_COMPAT, 'UTF-8'); ?>" title="Numéro" onkeypress="return submitonenter(event, 'thread_delete')"/>
<?php if ($confirm_delete_thread): ?>
<input class="submit submit_confirm" id="thread_confirmdelete" name="thread_confirmdelete" type="submit" value="Confirmer" />
<?php endif; ?>
</p>
<?php endif; ?>
</form>
<?php
$focus=false;
if ($missing_new_thread_title or $missing_new_thread_name or $bad_new_thread_name) {
	 $focus='#new_thread_title';
}
else if ($bad_new_thread_number) {
	$focus='#new_thread_number';
}
else if ($missing_old_thread_number or $bad_old_thread_number) {
	$focus='#old_thread_number';
}
else if ($confirm_delete_thread) {
	$focus='#old_thread_number';
}
?>
<?php if ($focus): ?>
<?php head('javascript', 'jquery.scrollTo', 'screen'); ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus(); $.scrollTo('<?php echo $focus; ?>', {offset: -200}); });
</script>
<?php endif; ?>
