<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    7
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<h3><?php echo htmlspecialchars($site_title ? $site_title : $sitename, ENT_COMPAT, 'UTF-8'); ?></h3>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php echo $inlanguages; ?>
</p>
<p>
<input id="thread_create" name="thread_create" type="submit" value="Ajouter" />
le fil
<input id="new_thread_title" name="new_thread_title" type="text" size="50" maxlength="100" value="<?php echo htmlspecialchars($new_thread_title, ENT_COMPAT, 'UTF-8'); ?>" title="Titre" onkeypress="return focusonenter(event, 'new_thread_number')"/>
#
<input id="new_thread_number" name="new_thread_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($new_thread_number, ENT_COMPAT, 'UTF-8'); ?>" title="Numéro" onkeypress="return submitonenter(event, 'thread_create')"/>
type
<?php global $supported_threads; ?>
<select name="new_thread_type" size="1">
<option value="thread"<?php if ($new_thread_type == 'thread'): ?> selected="selected"<?php endif; ?>>Fil</option>
<?php foreach ($supported_threads as $thd): ?>
<?php if ($thd == 'folder'): ?>
<option value="folder"<?php if ($new_thread_type == 'folder'): ?> selected="selected"<?php endif; ?>>Dossier</option>
<?php elseif ($thd == 'story'): ?>
<option value="story"<?php if ($new_thread_type == 'story'): ?> selected="selected"<?php endif; ?>>Article</option>
<?php elseif ($thd == 'book'): ?>
<option value="book"<?php if ($new_thread_type == 'book'): ?> selected="selected"<?php endif; ?>>Manuel</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
</p>
<?php if ($thread_list): ?>
<fieldset>
<legend>Catalogue</legend>
<table cellpadding="2" cellspacing="0">
<tbody>
<?php
$i=1;
foreach ($thread_list as $b) {
	extract($b);	/* pos, thread_id, thread_title, thread_number, thread_url */
	$thread_title = htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8');
	$thread_url .= '?' . 'clang=' . $clang;
	echo <<<_MARK_
<tr><td><input name="p[$i]" type="text" size="2" maxlength="3" value="$pos" /></td><td class="aright"><a href="$thread_url">$thread_id</a></td><td><a href="$thread_url">$thread_title</a></td></tr>\n
_MARK_;
	$i++;
}
?>
</tbody>
</table>
</fieldset>
<p>
<input id="threadlist_reorder" name="threadlist_reorder" type="submit" value="Trier" />
la liste ou
<input id="thread_delete" name="thread_delete" type="submit" value="Supprimer" />
le fil #
<input id="old_thread_number" name="old_thread_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($old_thread_number, ENT_COMPAT, 'UTF-8'); ?>" title="Numéro" onkeypress="return submitonenter(event, 'thread_delete')"/>
<?php if ($confirm_delete_thread): ?>
<input id="thread_confirmdelete" name="thread_confirmdelete" type="submit" value="Confirmer" />
<?php endif; ?>
</p>
<?php endif; ?>
</form>
<?php
$focus=false;
if ($missing_new_thread_title or $missing_new_thread_name or $bad_new_thread_name) {
	 $focus='#new_thread_title';
}
else if ($bad_new_thread_number) {
	$focus='#new_thread_number';
}
else if ($missing_old_thread_number or $bad_old_thread_number) {
	$focus='#old_thread_number';
}
else if ($confirm_delete_thread) {
	$focus='#old_thread_number';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
