<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php $scroll_to=false; ?>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php if (in_array('fr', $supported_languages)): ?>
<input name="fr" type="image" src="<?php echo $base_path; ?>/images/theme/flags/fr.png" alt="fr" title="Français"/>
<?php endif; ?>
<?php if (in_array('en', $supported_languages)): ?>
<input name="en" type="image" src="<?php echo $base_path; ?>/images/theme/flags/en.png" alt="en" title="English"/>
<?php endif; ?>
</p>
<p>
<input id="thread_title" name="thread_title" type="text" size="40" maxlength="100" value="<?php echo $thread_title; ?>" title="Titre" onkeypress="return submitonenter(event, 'thread_edit')"/>
<label>URL :</label>
<input id="thread_name" name="thread_name" type="text" size="40" maxlength="100" value="<?php echo $thread_name; ?>" onkeypress="return submitonenter(event, 'thread_edit')"/>
</p>
<p><label>Extrait :</label></p>
<p>
<textarea id="thread_abstract" name="thread_abstract" cols="80" rows="5"><?php echo $thread_abstract; ?></textarea>
<br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" />
</p>
<p><label>Nuage :</label></p>
<p>
<textarea name="thread_cloud" cols="80" rows="5"><?php echo $thread_cloud; ?></textarea><br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" />
</p>
<p>
<label>Type :</label>
<select name="thread_type" size="1">
<option value="thread" <?php echo $thread_type == 'thread' ? 'selected="selected"' : ''; ?>>Fil</option>
<option value="folder" <?php echo $thread_type == 'folder' ? 'selected="selected"' : ''; ?>>Dossier</option>
<option value="story" <?php echo $thread_type == 'story' ? 'selected="selected"' : ''; ?>>Article</option>
<option value="book" <?php echo $thread_type == 'book' ? 'selected="selected"' : ''; ?>>Manuel</option>
</select>
</p>
<p>
<input name="thread_search" type="checkbox" <?php if ($thread_search) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/search.png" alt="" />
<input name="thread_tag" type="checkbox" <?php if ($thread_tag) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/tag.png" alt="" />
<input name="thread_comment" type="checkbox" <?php if ($thread_comment) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/comment.png" alt="" />
<input name="thread_morecomment" type="checkbox" <?php if ($thread_morecomment) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/comment_add.png" alt="" />
</p>
<p>
<input id="thread_edit" name="thread_edit" type="submit" value="Éditer" />
</p>
<?php if ($missing_thread_title or $missing_thread_name or $bad_thread_name or $missing_thread_type or $bad_thread_type): ?>
<div class="alert">
<?php if ($missing_thread_title): ?>
<p>Vous n'avez pas saisi le titre du fil.</p>
<?php endif; ?>
<?php if ($missing_thread_name): ?>
<p>Spécifiez un nom pour le lien sur le fil.</p>
<?php elseif ($bad_thread_name): ?>
<p>Le nom du lien sur le fil est invalide.</p>
<?php endif; ?>
<?php if ($missing_thread_type): ?>
<p>Spécifiez le type du fil.</p>
<?php elseif ($bad_thread_type): ?>
<p>Le type de fil est invalide.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<script type="text/javascript">
<!--
$(document).ready(function() {
	$('.grippie').each(function() {
		var grippie = $(this);
		var textarea = grippie.prev().prev();
		var offset;

		grippie.mousedown(startDrag);

	    function startDrag(e) {
	      offset = textarea.height() - e.pageY;
	      textarea.css('opacity', 0.25);
	      $(document).mousemove(performDrag).mouseup(endDrag);
	      return false;
	    }

	    function performDrag(e) {
	      textarea.height(Math.max(32, offset + e.pageY) + 'px');
	      return false;
	    }

	    function endDrag(e) {
	      $(document).unbind('mousemove', performDrag).unbind('mouseup', endDrag);
	      textarea.css('opacity', 1);
	    }
	});
});
//-->
</script>
<h4>Contenu</h4>
<p>
<input id="node_create" name="node_create" type="submit" value="Ajouter" />
le contenu
<input id="new_node_title" name="new_node_title" type="text" size="50" maxlength="100" value="<?php echo $new_node_title; ?>" title="Titre" onkeypress="return focusonenter(event, 'new_node_number')"/>
#
<input id="new_node_number" name="new_node_number" type="text" size="3" maxlength="3" value="<?php echo $new_node_number; ?>" title="Numéro" onkeypress="return submitonenter(event, 'node_create')"/>
</p>
<?php if ($missing_new_node_title or $bad_new_node_title or $bad_new_node_number): ?>
<?php $scroll_to='#thread_edit'; ?>
<div class="alert">
<?php if ($missing_new_node_title): ?>
<p>Vous n'avez pas saisi le titre du nouveau contenu.</p>
<?php elseif ($bad_new_node_title): ?>
<p>Le titre du nouveau contenu est invalide.</p>
<?php endif; ?>
<?php if ($bad_new_node_number): ?>
<p>Le numéro du nouveau contenu n'est pas correct.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($thread_contents): ?>
<fieldset>
<legend>Sommaire</legend>
<table cellpadding="2" cellspacing="0">
<tbody>
<?php
$i=1;
$maxlen=strlen(count($thread_contents))+1;
foreach ($thread_contents as $c) {
	extract($c);	/* pos, node_id, node_title, node_number, node_url */
	$node_url .= '?' . 'clang=' . $clang;
	echo <<<_MARK_
<tr><td><input name="p[$i]" type="text" size="$maxlen" maxlength="3" value="$pos" /></td><td class="aright"><a href="$node_url">$node_number</a></td><td><a href="$node_url">$node_title</a></td></tr>\n
_MARK_;
	$i++;
}
?>
</tbody>
</table>
</fieldset>
<p>
<input id="thread_reorder" name="thread_reorder" type="submit" value="Trier" />
la liste ou
<input id="node_delete" name="node_delete" type="submit" value="Supprimer" />
le contenu #
<input id="old_node_number" name="old_node_number" type="text" size="3" maxlength="3" value="<?php echo $old_node_number; ?>" title="Numéro" onkeypress="return submitonenter(event, 'node_delete')"/>
</p>
<?php if ($missing_old_node_number or $bad_old_node_number): ?>
<?php $scroll_to='#node_delete'; ?>
<div class="alert">
<?php if ($missing_old_node_number): ?>
<p>Vous n'avez pas saisi le numéro du contenu à supprimer.</p>
<?php elseif ($bad_old_node_number): ?>
<p>Le numéro du contenu à supprimer est incorrect.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php endif; ?>
</form>
<?php if ($scroll_to): ?>
<script type="text/javascript">
<!--
$(document).ready(function() {
	$(window).scrollTo('<?php echo $scroll_to; ?>');
});
//-->
</script>
<?php endif; ?>
