<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php $scroll_to=false; ?>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php if (in_array('fr', $supported_languages)): ?>
<input name="fr" type="image" src="<?php echo $base_path; ?>/images/theme/flags/fr.png" alt="fr" title="Français"/>
<?php endif; ?>
<?php if (in_array('en', $supported_languages)): ?>
<input name="en" type="image" src="<?php echo $base_path; ?>/images/theme/flags/en.png" alt="en" title="English"/>
<?php endif; ?>
</p>
<p>
<input id="thread_create" name="thread_create" type="submit" value="Ajouter" />
le fil
<input id="new_thread_title" name="new_thread_title" type="text" size="50" maxlength="100" value="<?php echo $new_thread_title; ?>" title="Titre" onkeypress="return focusonenter(event, 'new_thread_number')"/>
#
<input id="new_thread_number" name="new_thread_number" type="text" size="3" maxlength="3" value="<?php echo $new_thread_number; ?>" title="Numéro" onkeypress="return submitonenter(event, 'thread_create')"/>
type
<?php
$selected=$new_thread_type ? $new_thread_type : 'thread';
?>
<select name="new_thread_type" size="1">
<option value="thread" <?php echo $selected == 'thread' ? 'selected="selected"' : ''; ?>>Fil</option>
<option value="folder" <?php echo $selected == 'folder' ? 'selected="selected"' : ''; ?>>Dossier</option>
<option value="story" <?php echo $thread_type == 'story' ? 'selected="selected"' : ''; ?>>Article</option>
<option value="book" <?php echo $selected == 'book' ? 'selected="selected"' : ''; ?>>Manuel</option>
</select>
</p>
<?php if ($missing_new_thread_title or $missing_new_thread_name or $missing_new_thread_type or $bad_new_thread_type or $bad_new_thread_number): ?>
<div class="alert">
<?php if ($missing_new_thread_title): ?>
<p>Vous n'avez pas saisi le titre du nouveau fil.</p>
<?php endif; ?>
<?php if ($missing_new_thread_name): ?>
<p>Spécifiez un nom pour le lien sur le nouveau fil.</p>
<?php elseif ($bad_new_thread_name): ?>
<p>Le nom du lien sur le nouveau fil est invalide.</p>
<?php endif; ?>
<?php if ($missing_new_thread_type): ?>
<p>Spécifiez le type du fil.</p>
<?php elseif ($bad_new_thread_type): ?>
<p>Le type de fil est invalide.</p>
<?php endif; ?>
<?php if ($bad_new_thread_number): ?>
<p>Le numéro du nouveau fil n'est pas correct.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($thread_list): ?>
<fieldset>
<legend>Catalogue</legend>
<table cellpadding="2" cellspacing="0">
<tbody>
<?php
$i=1;
$maxlen=strlen(count($thread_list))+1;
foreach ($thread_list as $b) {
	extract($b);	/* pos, thread_id, thread_title, thread_number, thread_url */
	$thread_url .= '?' . 'clang=' . $clang;
	echo <<<_MARK_
<tr><td><input name="p[$i]" type="text" size="$maxlen" maxlength="3" value="$pos" /></td><td class="aright"><a href="$thread_url">$thread_number</a></td><td><a href="$thread_url">$thread_title</a></td></tr>\n
_MARK_;
	$i++;
}
?>
</tbody>
</table>
</fieldset>
<p>
<input id="threadlist_reorder" name="threadlist_reorder" type="submit" value="Trier" />
la liste ou
<input id="thread_delete" name="thread_delete" type="submit" value="Supprimer" />
le fil #
<input id="old_thread_number" name="old_thread_number" type="text" size="3" maxlength="3" value="<?php echo $old_thread_number; ?>" title="Numéro" onkeypress="return submitonenter(event, 'thread_delete')"/>
<?php if ($confirm_delete_thread): ?>
Vraiment&nbsp;?&nbsp;<button id="thread_confirmdelete" name="thread_confirmdelete" type="submit">Confirmer</button>
<?php endif; ?>
</p>
<?php if ($missing_old_thread_number or $bad_old_thread_number): ?>
<?php $scroll_to='#thread_delete'; ?>
<div class="alert">
<?php if ($missing_old_thread_number): ?>
<p>Vous n'avez pas saisi le numéro du fil à supprimer.</p>
<?php elseif ($bad_old_thread_number): ?>
<p>Le numéro du fil à supprimer est incorrect.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php endif; ?>
</form>
<?php if ($scroll_to): ?>
<script type="text/javascript">
<!--
$(document).ready(function() {
	$(window).scrollTo('<?php echo $scroll_to; ?>');
});
//-->
</script>
<?php endif; ?>
