<?php

/**
 *
 * @copyright  2010-2014 izend.org
 * @version    7
 * @link       http://www.izend.org
 */
?>
<?php if ($ilike or $tweetit or $plusone or $linkedin or $pinit): ?>
<ul<?php if ($shareline): ?> id="shareline"<?php endif; ?> class="menu besocial">
<?php if ($linkedin): ?>
<li class="linkedin">
<?php echo $linkedin; ?>
</li>
<?php endif; ?>
<?php if ($tweetit): ?>
<li class="tweetit">
<?php echo $tweetit; ?>
</li>
<?php endif; ?>
<?php if ($pinit): ?>
<li class="pinit">
<?php echo $pinit; ?>
</li>
<?php endif; ?>
<?php if ($plusone): ?>
<li class="plusone">
<?php echo $plusone; ?>
</li>
<?php endif; ?>
<?php if ($ilike): ?>
<li class="ilike">
<?php echo $ilike; ?>
</li>
<?php endif; ?>
</ul>
<?php endif; ?>
<script type="text/javascript">
$(document).ready(function() {$('#shareline').show();});
</script>
