<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php if ($ilike or $tweetit or $plusone): ?>
<div class="social">
<?php if ($ilike): ?>
<div class="ilike">
<?php echo $ilike; ?>
</div>
<?php endif; ?>
<?php if ($tweetit): ?>
<div class="tweetit">
<?php echo $tweetit; ?>
</div>
<?php endif; ?>
<?php if ($plusone): ?>
<div class="plusone">
<?php echo $plusone; ?>
</div>
<?php endif; ?>
</div>
<?php endif; ?>
