<?php

/**
 *
 * @copyright  2010-2022 izend.org
 * @version    7
 * @link       http://www.izend.org
 */
?>
<div id="booksummary">
<?php if ($vote): ?>
<?php echo $vote; ?>
<?php endif; ?>
<h3><?php echo $book_title ? htmlspecialchars($book_title, ENT_COMPAT, 'UTF-8') : $book_id; ?></h3>
<?php if ($book_abstract): ?>
<p><?php echo htmlspecialchars($book_abstract, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($book_contents): ?>
<ol>
<?php foreach ($book_contents as $c): ?>
<?php extract($c);	/* page_title page_url */ ?>
<li><a href="<?php echo $page_url; ?>"><?php echo $page_title ? htmlspecialchars($page_title, ENT_COMPAT, 'UTF-8') : $page_id; ?></a></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
<?php if ($besocial): ?>
<?php echo $besocial; ?>
<?php endif; ?>
</div>
