<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<div id="bookpage">
<h3><?php echo htmlspecialchars($page_title ? $page_title : $page_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<p id="bookpagenav" class="menubar">
<?php if ($prev_page_url): ?>
<a href="<?php echo $prev_page_url; ?>"><img src="/images/theme/icons/left.png" alt=""/></a>
<a href="<?php echo $prev_page_url; ?>"><?php echo htmlspecialchars($prev_page_label, ENT_COMPAT, 'UTF-8'); ?></a>
<?php endif; ?>
<?php if ($next_page_url and $prev_page_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_page_url): ?>
<a href="<?php echo $next_page_url; ?>"><?php echo htmlspecialchars($next_page_label, ENT_COMPAT, 'UTF-8'); ?></a>
<a href="<?php echo $next_page_url; ?>"><img src="/images/theme/icons/right.png" alt=""/></a>
<?php endif; ?>
</p>
<?php if ($page_contents): ?>
<?php echo $page_contents; ?>
<?php if ($ilike or $tweetit or $plusone): ?>
<div class="social">
<?php if ($plusone): ?>
<div id="plusone">
<?php echo $plusone; ?>
</div>
<?php endif; ?>
<?php if ($tweetit): ?>
<div id="tweetit">
<?php echo $tweetit; ?>
</div>
<?php endif; ?>
<?php if ($ilike): ?>
<div id="ilike">
<?php echo $ilike; ?>
</div>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($page_comment): ?>
<?php echo $page_comment; ?>
<?php endif; ?>
<?php endif; ?>
</div>
