<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<?php if ($folder_title): ?>
<h3><?php echo $folder_title; ?></h3>
<?php endif; ?>
<?php if (!empty($folder_contents)): ?>
<ol>
<?php foreach ($folder_contents as $c):?>
<?php extract($c);	/* page_title page_url */ ?>
<li><a href="<?php echo $page_url; ?>"><?php echo htmlspecialchars($page_title, ENT_COMPAT, 'UTF-8'); ?></a></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
