<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    7
 * @link       http://www.izend.org
 */
?>
<?php if (isset($lang)): ?>
<meta http-equiv="content-type" content="text/html; charset=utf-8" lang="<?echo $lang; ?>" />
<?php else: ?>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<?php endif; ?>
<?php if (false): ?>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<?php endif; ?>
<?php if (!empty($description)): ?>
<meta name="description" content="<?php echo htmlspecialchars($description, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<?php endif; ?>
<?php if (!empty($keywords)): ?>
<meta name="keywords" content="<?php echo htmlspecialchars($keywords, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<?php endif; ?>
<meta name="generator" content="iZend" />
<?php if (!empty($author)): ?>
<meta name="author" content="<?php echo htmlspecialchars($author, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<?php endif; ?>
<?php if (!empty($robots)): ?>
<meta name="robots" content="<?php echo $robots; ?>" />
<?php else: ?>
<meta name="robots" content="index, follow" />
<?php endif; ?>
<meta property="og:title" content="<?php echo htmlspecialchars((isset($title) and $title) ? $title : $sitename, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<?php echo $base_url; ?>/<?php echo $request_path; ?>" />
<meta property="og:image" content="<?php echo $base_url; ?>/logos/siteqr.png" />
<?php if (!empty($description)): ?>
<meta property="og:description" content="<?php echo htmlspecialchars($description, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<?php endif; ?>
<meta property="og:site_name" content="<?php echo $sitename; ?>" />
<?php if (!empty($facebookid)): ?>
<meta property="fb:admins" content="<?php echo $facebookid; ?>" />
<?php endif; ?>
<?php if (!empty($favicon)): ?>
<link rel="shortcut icon" href="<?php echo $base_path; ?>/<?php echo $favicon; ?>.ico" type="image/x-icon" />
<?php endif; ?>
<?php if (true): ?>
<link href="<?php echo $base_path; ?>/css/zero.css" rel="stylesheet" type="text/css" media="screen" />
<?php endif; ?>
<link href="<?php echo $base_path; ?>/css/screen.css" rel="stylesheet" type="text/css" media="screen" />
<link href="<?php echo $base_path; ?>/css/theme.css" rel="stylesheet" type="text/css" media="screen" />
<link href="<?php echo $base_path; ?>/css/print.css" rel="stylesheet" type="text/css" media="print" />
<link href="<?php echo $base_path; ?>/css/<?php echo $lang; ?>.css" rel="stylesheet" type="text/css" media="screen" />
<?php if (!empty($stylesheets)): ?>
<?php foreach ($stylesheets as $css) : ?>
<?php
$name=$css['name'];
$media=isset($css['media']) ? $css['media'] : '';
if (substr_compare($name, 'http://', 0, 7) == 0 or substr_compare($name, 'https://', 0, 8) == 0) {
	$url=$name;
}
else if (substr_compare($name, '.css', -4, 4) == 0) {
	$url=$base_path . '/css/' . $name;
}
else {
	$url=$base_path . '/css/' . $name . '.css';
}
?>
<link href="<?php echo $url; ?>" rel="stylesheet" type="text/css" media="<?php echo $media; ?>" />
<?php endforeach; ?>
<?php endif; ?>
<?php if (!empty($javascripts)): ?>
<?php foreach ($javascripts as $js) : ?>
<?php
$name=$js['name'];
$param=isset($js['param']) ? $js['param'] : '';
if (substr_compare($name, 'http://', 0, 7) == 0 or substr_compare($name, 'https://', 0, 8) == 0) {
	$url=$name;
}
else if (substr_compare($name, '.js', -3, 3) == 0) {
	$url=$base_path . '/js/' . $name;
}
else {
	$url=$base_path . '/js/' . $name . '.js';
}
?>
<script type="text/javascript" src="<?php echo $url; ?>"><?php echo $param; ?></script>
<?php endforeach; ?>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $base_path; ?>/js/tools.js"></script>
<title><?php echo htmlspecialchars((isset($title) and $title) ? $title : $sitename, ENT_NOQUOTES, 'UTF-8', false); ?></title>
