<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    20
 * @link       http://www.izend.org
 */
?>
<?php if (!empty($lang)): ?>
<meta http-equiv="content-type" content="text/html; charset=utf-8" lang="<?php echo $lang; ?>" />
<?php else: ?>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<?php endif; ?>
<?php if (false): ?>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<?php endif; ?>
<?php if (!empty($description)): ?>
<meta name="description" content="<?php echo htmlspecialchars($description, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<?php endif; ?>
<?php if (!empty($keywords)): ?>
<meta name="keywords" content="<?php echo htmlspecialchars($keywords, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<?php endif; ?>
<meta name="generator" content="iZend" />
<?php if (!empty($author)): ?>
<meta name="author" content="<?php echo htmlspecialchars($author, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<?php endif; ?>
<?php if (!empty($date)): ?>
<meta name="date" content="<?php echo date('Y-m-d', $date); ?>" />
<?php endif; ?>
<?php if (!empty($robots)): ?>
<meta name="robots" content="<?php echo $robots; ?>" />
<?php else: ?>
<meta name="robots" content="index, follow" />
<?php endif; ?>
<?php require_once 'isagent.php'; ?>
<?php if (is_facebook()): ?>
<meta property="og:title" content="<?php echo htmlspecialchars(!empty($title) ? $title : $sitename, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<?php echo $base_url; ?>/<?php echo $request_path; ?>" />
<meta property="og:image" content="<?php echo $base_url; ?>/logos/sitefb.png" />
<?php if (!empty($description)): ?>
<meta property="og:description" content="<?php echo htmlspecialchars($description, ENT_NOQUOTES, 'UTF-8', false); ?>" />
<?php endif; ?>
<meta property="og:site_name" content="<?php echo $sitename; ?>" />
<?php if (!empty($facebookid)): ?>
<meta property="fb:admins" content="<?php echo $facebookid; ?>" />
<?php endif; ?>
<?php endif; ?>
<?php if (false): ?>
<meta name="viewport" content="initial-scale=1.0">
<?php endif; ?>
<?php if (!empty($canonical)): ?>
<link rel="canonical" href="<?php echo $canonical; ?>" />
<?php else: ?>
<link rel="canonical" href="<?php echo $base_url;?>/<?php echo $request_path; ?>" />
<?php endif; ?>
<?php if ($lang): ?>
<link rel="alternate" href="<?php echo $base_url; ?>/<?php echo $lang; ?>/rss" type="application/rss+xml" title="<?php echo $sitename; ?> RSS" />
<?php else: ?>
<link rel="alternate" href="<?php echo $base_url; ?>/rss" type="application/rss+xml" title="<?php echo $sitename; ?> RSS" />
<?php endif; ?>
<?php if (!empty($favicon)): ?>
<link rel="shortcut icon" href="<?php echo $base_path; ?>/<?php echo $favicon; ?>.ico" type="image/x-icon" />
<?php endif; ?>
<?php if (true): ?>
<link href="<?php echo $base_path; ?>/css/zero.css" rel="stylesheet" type="text/css" media="screen" />
<?php endif; ?>
<link href="<?php echo $base_path; ?>/css/screen.css" rel="stylesheet" type="text/css" media="screen" />
<link href="<?php echo $base_path; ?>/css/theme.css" rel="stylesheet" type="text/css" media="screen" />
<?php if (!empty($lang)): ?>
<link href="<?php echo $base_path; ?>/css/<?php echo $lang; ?>.css" rel="stylesheet" type="text/css" media="screen" />
<?php endif; ?>
<?php if (!empty($stylesheets)): ?>
<?php foreach ($stylesheets as $css) : ?>
<?php
$name=$css['name'];
$media=isset($css['media']) ? $css['media'] : 'all';
if ($name[0] == '/' or substr_compare('http://', $name, 0, 7) == 0 or substr_compare('https://', $name, 0, 8) == 0) {
	$url=$name;
}
else if (substr_compare('.css', $name, -4, 4) == 0) {
	$url=$base_path . '/css/' . $name;
}
else {
	$url=$base_path . '/css/' . $name . '.css';
}
?>
<link href="<?php echo $url; ?>" rel="stylesheet" type="text/css" media="<?php echo $media; ?>" />
<?php endforeach; ?>
<?php endif; ?>
<?php if (!empty($theme)): ?>
<link href="<?php echo $base_path; ?>/css/themes/<?php echo $theme; ?>.css" rel="stylesheet" type="text/css" media="screen" />
<?php endif; ?>
<link href="<?php echo $base_path; ?>/css/print.css" rel="stylesheet" type="text/css" media="print" />
<?php if (false): ?>
<link href="<?php echo $base_path; ?>/css/media.css" rel="stylesheet" type="text/css" />
<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1" />
<?php endif; ?>
<?php if (!empty($javascripts)): ?>
<?php foreach ($javascripts as $js) : ?>
<?php
$name=$js['name'];
$param=isset($js['param']) ? $js['param'] : '';
if ($name[0] == '/' or substr_compare('http://', $name, 0, 7) == 0 or substr_compare('https://', $name, 0, 8) == 0) {
	$url=$name;
}
else if (substr_compare('.js', $name, -3, 3) == 0) {
	$url=$base_path . '/js/' . $name;
}
else {
	$url=$base_path . '/js/' . $name . '.js';
}
?>
<script type="text/javascript" src="<?php echo $url; ?>"><?php echo $param; ?></script>
<?php endforeach; ?>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $base_path; ?>/js/tools.js"></script>
<title><?php echo htmlspecialchars(!empty($title) ? $title : $sitename, ENT_NOQUOTES, 'UTF-8', false); ?></title>
