<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php if ($headline_url or $headline_text): ?>
<div id="headline">
<ul class="menu menubar">
<?php if ($headline_url): ?>
<li><a href="<?php echo $headline_url; ?>"><?php echo htmlspecialchars($headline_text, ENT_NOQUOTES, 'UTF-8', false); ?></a></li>
<?php else: ?>
<li><?php echo htmlspecialchars($headline_text, ENT_NOQUOTES, 'UTF-8', false); ?></li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>
