<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php global $supported_languages; ?>
<?php foreach ($supported_languages as $lang): ?>
<?php if ($lang == 'fr'): ?>
<input name="<?php echo $lang; ?>" type="submit" class="lang <?php echo $lang; ?> submit<?php if ($lang == $clang): ?> selected<?php endif; ?>" value="Français" />
<?php elseif ($lang == 'en'): ?>
<input name="<?php echo $lang; ?>" type="submit" class="lang <?php echo $lang; ?> submit<?php if ($lang == $clang): ?> selected<?php endif; ?>" value="English" />
<?php elseif ($lang == 'ar'): ?>
<input name="<?php echo $lang; ?>" type="submit" class="lang <?php echo $lang; ?> submit<?php if ($lang == $clang): ?> selected<?php endif; ?>" value="عربي" />
<?php endif; ?>
<?php endforeach; ?>
