<?php

/**
 *
 * @copyright  2010-2017 izend.org
 * @version    5
 * @link       http://www.izend.org
 */
?>
<?php global $supported_languages; ?>
<?php foreach ($supported_languages as $lang): ?>
<?php if ($lang == 'fr'): ?>
<a class="lang fr<?php if ($lang == $clang): ?> selected<?php endif; ?>" href="?clang=fr" title="Français"><span>fr</span></a>
<?php elseif ($lang == 'en'): ?>
<a class="lang en<?php if ($lang == $clang): ?> selected<?php endif; ?>" href="?clang=en" title="English"><span>en</span></a>
<?php elseif ($lang == 'de'): ?>
<a class="lang de<?php if ($lang == $clang): ?> selected<?php endif; ?>" href="?clang=de" title="Deutsch"><span>de</span></a>
<?php elseif ($lang == 'it'): ?>
<a class="lang it<?php if ($lang == $clang): ?> selected<?php endif; ?>" href="?clang=it" title="Italiano"><span>it</span></a>
<?php elseif ($lang == 'es'): ?>
<a class="lang es<?php if ($lang == $clang): ?> selected<?php endif; ?>" href="?clang=es" title="Español"><span>es</span></a>
<?php elseif ($lang == 'ru'): ?>
<a class="lang ru<?php if ($lang == $clang): ?> selected<?php endif; ?>" href="?clang=ru" title="Pусский"><span>ru</span></a>
<?php endif; ?>
<?php endforeach; ?>
