<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    5
 * @link       http://www.izend.org
 */
?>
<ul class="languages menu menubar">
<?php if ($fr_page): ?>
<li><a class="btn_fr" href="<?php echo $fr_page; ?>" title="Version française"><span>Français (France)</span></a></li>
<?php endif; ?>
<?php if ($en_page): ?>
<li><a class="btn_en" href="<?php echo $en_page; ?>" title="English version"><span>English (US)</span></a></li>
<?php endif; ?>
</ul>
