<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<ul id="languages" class="menu menubar">
<?php if ($fr_page): ?>
<li><a class="btn_fr" href="<?php echo $fr_page; ?>" title="Version française"><span>Français</span></a></li>
<?php endif; ?>
<?php if ($en_page): ?>
<li><a class="btn_en" href="<?php echo $en_page; ?>" title="English version"><span>English</span></a></li>
<?php endif; ?>
</ul>
