<?php

/**
 *
 * @copyright  2012 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<div id="newslettersummary">
<h3><?php echo htmlspecialchars($newsletter_title ? $newsletter_title : $newsletter_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<?php if ($newsletter_abstract): ?>
<p><?php echo htmlspecialchars($newsletter_abstract, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($newsletter_contents): ?>
<ol>
<?php foreach ($newsletter_contents as $c): ?>
<?php extract($c);	/* page_title page_url */ ?>
<li><a href="<?php echo $page_url; ?>"><?php echo htmlspecialchars($page_title ? $page_title : $page_id, ENT_COMPAT, 'UTF-8'); ?></a></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
</div>
