<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    12
 * @link       http://www.izend.org
 */
?>
<?php
foreach ($contents as $c) {
	switch($c['type']) {
		case 'text':
			$s = $c['text'];
			if ($s) {
				echo $s, PHP_EOL;
			}
			break;
		case 'file':
			$file_content = $c['file'];
			if ($file_content) {
				echo '<div class="file">', PHP_EOL, $file_content, PHP_EOL,'</div>', PHP_EOL;
			}
			break;
		case 'download':
			$file = htmlspecialchars($c['file'], ENT_COMPAT, 'UTF-8');
			$download_url = $c['download_url'];
			echo '<div class="download">', PHP_EOL, '<a href="', $download_url, '" rel="nofollow">', $file, '</a>', PHP_EOL, '</div>', PHP_EOL;
			break;
		case 'infile':
			include $c['infile'];
			break;
		case 'youtube':
			extract($c);	/* id width height autoplay theme rel */
			echo '<div class="youtube" style="max-width:', $width, 'px;">', PHP_EOL;
			echo '<div style="width:', $width, 'px;padding-bottom:', round($height/$width, 2) * 100, '%;">', PHP_EOL;
			echo '<iframe frameborder="0" width="', $width, '" height="', $height, '" src="http://www.youtube.com/embed/', $id, '?autoplay=', $autoplay, '&amp;autohide=1&amp;controls=1&amp;HD=1&amp;fs=0&amp;modestbranding=0&amp;showinfo=0&amp;rel=', $rel, '&amp;theme=', $theme, '"></iframe>', PHP_EOL;
			echo '</div>', PHP_EOL;
			echo '</div>', PHP_EOL;
			break;
		case 'longtail':
			extract($c);	/* file image width height skin icons controlbar duration autostart repeat */
			$id = uniqid('id');
			echo '<div class="longtail">', PHP_EOL;
			echo '<div id="', $id, '"></div>', PHP_EOL;
			echo '<script type="text/javascript">', PHP_EOL;
			echo '//<![CDATA[', PHP_EOL;
			echo 'var w=', $width,', h=', $height, ', maxw=$(window).innerWidth();', PHP_EOL;
			echo 'if (maxw < w) {', PHP_EOL;
			echo '    h=Math.floor(h*maxw/w);', PHP_EOL;
			echo '    w=maxw;', PHP_EOL;
			echo '}', PHP_EOL;
			echo 'jwplayer("', $id, '").setup({', PHP_EOL;
			if (true) {
				echo '    flashplayer: "', $base_path, '/longtail/player.swf",', PHP_EOL;
			}
			echo '    id: "', $id, '",', PHP_EOL;
			echo '    width: w,', PHP_EOL;
			echo '    height: h,', PHP_EOL;
			if ($image) {
				echo '    image: "', $base_path, $image, '",', PHP_EOL;
			}
			if (false) {
				echo '    modes: [', PHP_EOL;
				echo '        { type: "html5" },', PHP_EOL;
				echo '        { type: "flash", src: "', $base_path, '/longtail/player.swf" },', PHP_EOL;
				echo '        { type: "download" },', PHP_EOL;
				echo '    ],', PHP_EOL;
			}
			$levels=preg_split('/[\s]+/', $file);
			switch (count($levels)) {
				case 1:
					echo '    file: "', $base_path, $file, '",', PHP_EOL;
					break;
				default:
					echo '    levels: [', PHP_EOL;
					foreach ($levels as $file) {
						echo '        { file: "', $base_path, $file, '" },', PHP_EOL;
					}
					echo '    ],', PHP_EOL;
					break;
			}
			if ($duration) {
				echo '    duration: "', $duration, '",', PHP_EOL;
			}
			if ($skin) {
				echo '    skin: "', $base_path, $skin, '",', PHP_EOL;
			}
			echo '    controlbar: "', $controlbar, '",', PHP_EOL;
			echo '    icons: "', $icons ? 'true' : 'false', '",', PHP_EOL;
			echo '    repeat: "', $repeat ? 'always' : 'none', '",', PHP_EOL;
			echo '    autostart: "', $autostart ? 'true' : 'false', '",', PHP_EOL;
			echo '    screencolor: "ffffff"', PHP_EOL;
			echo '});', PHP_EOL;
			echo '//]]>', PHP_EOL;
			echo '</script>', PHP_EOL;
			echo '</div>', PHP_EOL;
			break;
		default:
			break;
	}
}
?>
