<?php

/**
 *
 * @copyright  2010-2026 izend.org
 * @version    11
 * @link       http://www.izend.org
 */
?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>', "\n"; ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
	<atom:link href="<?php echo $base_url; ?><?php echo $rssfeed_page; ?>" rel="self" type="application/rss+xml" />
	<title><?php echo htmlspecialchars($sitename, ENT_XML1, 'UTF-8'); ?></title>
<?php if ($lang): ?>
	<link><?php echo $base_url; ?>/<?php echo $lang; ?></link>
<?php else: ?>
	<link><?php echo $base_url; ?></link>
<?php endif; ?>
<?php if ($description): ?>
	<description><?php echo htmlspecialchars($description, ENT_XML1, 'UTF-8'); ?></description>
<?php endif; ?>
<?php if ($lang): ?>
	<language><?php echo $lang; ?></language>
<?php endif; ?>
	<pubDate><?php echo date('r'); ?></pubDate>
	<lastBuildDate><?php echo date('r'); ?></lastBuildDate>
	<copyright><?php echo $sitename; ?></copyright>
	<image>
		<title><?php echo $sitename; ?></title>
<?php if ($lang): ?>
		<link><?php echo $base_url; ?>/<?php echo $lang; ?></link>
<?php else: ?>
		<link><?php echo $base_url; ?></link>
<?php endif; ?>
		<url><?php echo $base_url; ?>/logos/siteqr.png</url>
		<width>50</width>
	</image>
<?php if ($itemlist): ?>
<?php foreach ($itemlist as $item): ?>
<?php extract($item) ?>
	<item>
		<title><?php echo htmlspecialchars($title, ENT_XML1, 'UTF-8'); ?></title>
<?php if ($uri): ?>
		<link><?php echo $base_url; ?><?php echo $uri; ?></link>
		<guid><?php echo $base_url; ?><?php echo $uri; ?></guid>
<?php endif; ?>
<?php if ($description): ?>
		<description><?php echo htmlspecialchars($description, ENT_XML1, 'UTF-8'); ?></description>
<?php endif; ?>
<?php if ($image_uri): ?>
		<enclosure type="<?php echo $image_type; ?>" url="<?php echo $base_url; ?><?php echo $image_uri; ?>" length="<?php echo $image_size; ?>" />
<?php endif; ?>
		<pubDate><?php echo date('r', $created); ?></pubDate>
	</item>
<?php endforeach; ?>
<?php endif; ?>
</channel>
</rss>
