<?php

/**
 *
 * @copyright  2010-2018 izend.org
 * @version    6
 * @link       http://www.izend.org
 */
?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>', "\n"; ?>
<rss version="2.0">
<channel>
	<title><![CDATA[<?php echo htmlspecialchars($sitename, ENT_COMPAT, 'UTF-8'); ?>]]></title>
<?php if ($lang): ?>
	<link><?php echo $base_url; ?>/<?php echo $lang; ?></link>
<?php else: ?>
	<link><?php echo $base_url; ?></link>
<?php endif; ?>
<?php if ($description): ?>
	<description><![CDATA[<?php echo htmlspecialchars($description, ENT_COMPAT, 'UTF-8'); ?>]]></description>
<?php endif; ?>
<?php if ($lang): ?>
	<language><?php echo $lang; ?></language>
<?php endif; ?>
	<pubDate><?php echo date('r', mktime(13, 10, 0, 5, 13, 2010)); ?></pubDate>
	<lastBuildDate><?php echo date('r'); ?></lastBuildDate>
	<copyright><?php echo $sitename; ?></copyright>
	<image>
		<title><?php echo $sitename; ?></title>
<?php if ($lang): ?>
		<link><?php echo $base_url; ?>/<?php echo $lang; ?></link>
<?php else: ?>
		<link><?php echo $base_url; ?></link>
<?php endif; ?>
		<url><?php echo $base_url; ?>/logos/siteqr.png</url>
		<width>50</width>
	</image>
<?php if ($itemlist): ?>
<?php foreach ($itemlist as $item): ?>
<?php extract($item) ?>
	<item>
		<title><![CDATA[<?php echo htmlspecialchars($title, ENT_COMPAT, 'UTF-8'); ?>]]></title>
<?php if ($uri): ?>
		<link><?php echo $base_url; ?>/<?php echo urlencode($url); ?></link>
<?php endif; ?>
		<description>
		<![CDATA[<?php echo htmlspecialchars($description, ENT_COMPAT, 'UTF-8'); ?>]]>
		</description>
		<pubDate><?php echo date('r', $created); ?></pubDate>
	</item>
<?php endforeach; ?>
<?php endif; ?>
</channel>
</rss>
