<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>', "\n"; ?>
<rss version="2.0">
<channel>
	<title><![CDATA[<?php echo $sitename; ?>]]></title>
	<link><?php echo $base_url; ?>/<?php echo $lang; ?></link>
	<description><![CDATA[<?php echo $description; ?>]]></description>
	<language><?php echo $lang; ?></language>
	<pubDate><?php echo date('r', mktime(13, 10, 0, 5, 13, 2010)); ?></pubDate>
	<lastBuildDate><?php echo date('r', mktime(23, 30, 0, 7, 28, 2011)); ?></lastBuildDate>
	<copyright><?php echo $sitename; ?></copyright>
	<image>
		<title><?php echo $sitename; ?></title>
		<link><?php echo $base_url; ?>/<?php echo $lang; ?></link>
		<url><?php echo $base_url; ?>/logos/sitelogo.png</url>
		<width>300</width>
	</image>
<?php foreach ($itemlist as $item): ?>
<?php extract($item) ?>
	<item>
		<guid><?php echo $base_url; ?>/<?php echo $uri; ?></guid>
		<title><![CDATA[<?php echo $title; ?>]]></title>
		<link><?php echo $base_url; ?>/<?php echo $uri; ?></link>
		<description>
		<![CDATA[<?php echo $description; ?>]]>
		</description>
		<pubDate><?php echo date('r', $created); ?></pubDate>
	</item>
<?php endforeach; ?>
</channel>
</rss>
