<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<div id="searchlinks">
<?php if ($linklist): ?>
<?php foreach ($linklist as $id => $data): ?>
<?php extract($data); /* thread_title thread_url content */ ?>
<?php if ($thread_title): ?>
<h3><?php echo htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8'); ?></h3>
<?php endif; ?>
<ol>
<?php foreach ($content as $link): ?>
<?php extract($link); /* link_title link_url link_description link_cloud */ ?>
<li>
<a href="<?php echo $link_url; ?>"><span><?php echo htmlspecialchars($link_title, ENT_COMPAT, 'UTF-8'); ?></span></a>
<p><?php echo htmlspecialchars($link_description, ENT_COMPAT, 'UTF-8'); ?></p>
<p><?php echo $link_cloud; /* already escaped */ ?></p>
</li>
<?php endforeach; ?>
</ol>
<?php endforeach; ?>
<?php endif; ?>
</div>
