<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<div id="searchlinks">
<?php if ($linklist): ?>
<ul>
<?php
foreach ($linklist as $link) {
	extract($link);	/*  */
?>
<li>
<a href="<?php echo $link_url; ?>"><span><?php echo $link_title; ?></span></a>
<p><?php echo $link_description; ?></p>
<p><?php echo $link_cloud; ?></p>
</li>
<?php
}
?>
</ul>
<?php endif; ?>
</div>
