<?php

/**
 *
 * @copyright  2010-2018 izend.org
 * @version    12
 * @link       http://www.izend.org
 */
?>
<?php if ($ilike or $tweetit or $plusone or $linkedin or $pinit): ?>
<ul id="sharebar" class="sidebar <?php echo $sharemode; ?>">
<?php if ($sharemode == 'standard'): ?>
<?php if ($ilike): ?>
<li class="facebook">
<?php echo $ilike; ?>
</li>
<?php endif; ?>
<?php if ($tweetit): ?>
<li class="twitter">
<?php echo $tweetit; ?>
</li>
<?php endif; ?>
<?php if ($linkedin): ?>
<li class="linkedin">
<?php echo $linkedin; ?>
</li>
<?php endif; ?>
<?php if ($pinit): ?>
<li class="pinterest">
<?php echo $pinit; ?>
</li>
<?php endif; ?>
<?php if ($plusone): ?>
<li class="gplus">
<?php echo $plusone; ?>
</li>
<?php endif; ?>
<?php else: ?>
<?php if ($ilike): ?>
<li class="facebook">
<?php echo $ilike; ?>
</li>
<?php endif; ?>
<?php if ($tweetit): ?>
<li class="twitter">
<?php echo $tweetit; ?>
</li>
<?php endif; ?>
<?php if ($plusone): ?>
<li class="gplus">
<?php echo $plusone; ?>
</li>
<?php endif; ?>
<?php if ($linkedin): ?>
<li class="linkedin">
<?php echo $linkedin; ?>
</li>
<?php endif; ?>
<?php if ($pinit): ?>
<li class="pinterest">
<?php echo $pinit; ?>
</li>
<?php endif; ?>
<?php endif; ?>
</ul>
<script>
$(document).ready(function() {$('#sharebar').show();});
</script>
<?php endif; ?>
