<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<?php if (true): ?>
<?php if (isset($search) and !empty($search)): ?>
<?php echo $search; ?>
<?php endif; ?>
<?php endif; ?>
<?php if (false): ?>
<?php if (isset($title) and !empty($title)): ?>
<?php echo $title; ?>
<?php endif; ?>
<?php endif; ?>
<?php if (isset($summary) and !empty($summary)): ?>
<ol id="summary" class="menu">
<?php foreach ($summary as $p): ?>
<?php list($title, $url)=$p; ?>
<li><a href="<?php echo $url; ?>"><?php echo htmlspecialchars($title, ENT_NOQUOTES, 'UTF-8', false); ?></a></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
<?php if (isset($cloud) and !empty($cloud)): ?>
<?php head('javascript', 'jquery.cookie'); ?>
<div id="cloudiness" class="hidy"></div>
<?php echo $cloud; ?>
<script type="text/javascript">
if ($.cookie('nocloud') == 1) {
		$('.cloud').hide();
}
$('#cloudiness').click(function() {
	$('.cloud').toggle();
	$.cookie('nocloud', $('.cloud').is(':hidden') ? 1 : 0, { path: '/' });
});
</script>
<?php endif; ?>
