<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<div id="story">
<h3><?php echo htmlspecialchars($page_title ? $page_title : $page_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<?php if ($page_contents): ?>
<?php echo $page_contents; ?>
<?php endif; ?>
<?php if ($besocial): ?>
<?php echo $besocial; ?>
<?php endif; ?>
<?php if ($page_comment): ?>
<?php echo $page_comment; ?>
<?php endif; ?>
</div>
