<?php

/**
 *
 * @copyright  2010-2016 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<?php if (!empty($thread_list)): ?>
<ol>
<?php foreach ($thread_list as $thread):
extract($thread);	/* thread_id thread_name thread_title thread_url */
?>
<li><a href="<?php echo $thread_url; ?>"><?php echo htmlspecialchars($thread_title ? $thread_title : $thread_id, ENT_COMPAT, 'UTF-8'); ?></a></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
