<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<h3>Gestion</h3>
<?php if (!empty($newsletter_page)): ?>
<p class="vignette"><a href="<?php echo $newsletter_page; ?>" rel="nofollow"><img src="/images/theme/envelopelarge.png" alt="" title="Infolettre" /></a></p>
<?php endif; ?>
<div id="userbalance">
<?php echo $balance; ?>
</div>
<h5>Contenu</h5>
<?php echo $upload; ?>
<h5>Communauté</h5>
<?php echo $usersearch; ?>
