<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<div id="bannermenu">
<ul class="menu menubar">
<?php if ($contact): ?>
<li><a id="mail" href="<?php echo $contact_page; ?>" rel="nofollow" title="Nous contacter"><span>Contact</span></a></li>
<?php endif; ?>
<?php if ($logout): ?>
<li><a id="exit" href="<?php echo $nobody_page; ?>" rel="nofollow" title="Déconnexion"><span>Déconnexion</span></a></li>
<?php endif; ?>
<?php if ($login): ?>
<li><a id="enter" href="<?php echo $user_page; ?>" rel="nofollow" title="Votre compte"><span>Compte</span></a></li>
<?php endif; ?>
<?php if ($account): ?>
<li><a id="account" href="<?php echo $account_page; ?>" rel="nofollow" title="Votre compte"><span>Compte</span></a></li>
<?php endif; ?>
<?php if ($edit): ?>
<li><a id="edit" href="<?php echo $edit_page; ?>" title="Éditer" rel="nofollow"><span>Éditer</span></a></li>
<?php elseif ($view): ?>
<li><a id="view" href="<?php echo $view_page; ?>" title="Voir" rel="nofollow"><span>Voir</span></a></li>
<?php endif; ?>
<?php if ($validate): ?>
<li><a id="validate" href="http://validator.w3.org/check?uri=<?php echo $base_url . $validate_page; ?>" target="validator.w3.org" rel="nofollow" title="Valider"><span>Valider</span></a></li>
<?php endif; ?>
<?php if ($admin): ?>
<li><a id="admin" href="<?php echo $admin_page; ?>" rel="nofollow" title="Gérer"><span>Gérer</span></a></li>
<?php endif; ?>
</ul>
</div>
