<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php require_once 'datefr.php'; ?>
<?php require_once 'bbcode.php'; ?>
<?php
$i=1;
foreach ($comments as $c) {
	extract($c);	/* comment_id, comment_text, comment_name, comment_mail, comment_created */
?>
<div class="comment">
<p><?php if ($comment_name): ?><img class="avatar noprint" src="/avatars/<?php echo $comment_name; ?>.png" alt="" title="<?php echo $comment_name; ?>" /> <?php endif; ?><span class="longdate">Le <?php echo longdate_fr($comment_created); ?> à <?php echo strftime("%H:%M:%S", $comment_created); ?></span><?php if ($comment_name): ?> <span class="author">par <?php echo $comment_name; ?></span><?php endif; ?></p>
<div><?php echo bbcode($comment_text); ?></div>
</div>
<?php
	$i++;
}
?>
