<?php

/**
 *
 * @copyright  2017 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3>Validation d'un compte</h3>
<?php extract($errors); ?>
<?php if ($bad_user): ?>
<p>Cet utilisateur n'est pas enregistré.</p>
<?php elseif ($bad_time): ?>
<p>Le délai autorisé pour cette opération est dépassé.
Un nouveau lien a été envoyé par email à votre adresse.</p>
<?php endif; ?>
<?php extract($infos); ?>
<div class="infos">
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($account_confirmed): ?>
<p>Votre compte a été validé.
Pour vous identifier, <a href="<?php echo $user_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
</div>
