<?php

/**
 *
 * @copyright  2013 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<span id="connectbar" class="menu noprint">
<?php if ($facebook_login_url): ?>
<a class="facebook" href="<?php echo htmlspecialchars($facebook_login_url, ENT_COMPAT, 'UTF-8'); ?>" title="Connectez-vous avec Facebook"><span>Facebook</span></a>
<?php endif; ?>
</span>
<script type="text/javascript">
$('#connectbar a').hover(function() { $(this).animate({'opacity' : '0.5'}, 200); }, function() { $(this).animate({'opacity' : '1.0'}, 200); } );
</script>
