<?php

/**
 *
 * @copyright  2016-2018 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<div id="consent">
<p>En utilisant ce site web, <b>vous acceptez l’utilisation de cookies</b> conformément à notre politique de données personnelles.
<?php if (true): ?>
<b>Notez</b> que les cookies de ce site web sont exemptés du recueil du consentement car
<i>strictement nécessaires à la fourniture d’un service expressément demandé par l’utilisateur</i>.
<?php endif; ?>
<?php if (false): ?>
Pour en savoir plus, <a href="/fr/informations-legales" title="Informations légales">cliquez ici</a>.
<?php endif; ?>
</p>
<?php if ($confirmcookieconsent): ?>
<p><span id="consentyes" class="clickit">J'ai compris</span></p>
<?php endif; ?>
</div>
<?php if ($confirmcookieconsent): ?>
<?php head('javascript', 'jquery.cookie'); ?>
<script type="text/javascript">
$('#consentyes').click(function() {
	$.cookie('cookieconsent', 1, { path: '/' });
	$('#consent').hide();
});
</script>
<?php endif; ?>
