<?php

/**
 *
 * @copyright  2016 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<div id="consent">
<p>En utilisant ce site web, <b>vous acceptez l’utilisation de cookies</b> conformément à notre politique de données personnelles.
<b>Notez</b> que les cookies de ce site web sont exemptés du recueil du consentement car
<i>strictement nécessaires à la fourniture d’un service expressément demandé par l’utilisateur</i>.</p>
<?php if (false): ?>
<p>Pour en savoir plus, <a href="#">cliquez ici</a>.</p>
<?php endif; ?>
</div>
