<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3>Donation</h3>
<p class="vignette"><img src="<?php echo $base_path; ?>/images/paypal_solutions.png" alt="" title="PayPal - La solution de paiement en ligne la plus simple et la plus sécurisée !"/></p>
<p>Merci de montrer votre appréciation du travail presenté par ce site en contribuant à son développement par un don.</p>
<?php echo $donateme; ?>
