<?php

/**
 *
 * @copyright  2013 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<div id="linkbar" class="noprint">
<a href="https://www.facebook.com/" target="_blank" title="Rejoignez-nous sur Facebook"><span class="icon_facebook">Facebook</span></a>
<a href="https://twitter.com/" target="_blank" title="Suivez-nous sur Twitter"><span class="icon_twitter">Twitter</span></a>
<a href="http://www.buzzmii.com/" target="_blank" title="Visitez notre page sur BuZZmii"><span class="icon_buzzmii">BuZZmii</span></a>
<a href="<?php echo $base_path; ?>/fr/rss" title="Inscrivez-vous au flux RSS"><span class="icon_rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/fr/infolettre/abonnement" title="Recevez notre lettre d'information"><span class="icon_newsletter">Infolettre</span></a>
</div>
