<?php

/**
 *
 * @copyright  2010-2015 izend.org
 * @version    6
 * @link       http://www.izend.org
 */
?>
<?php if ($mode == 'lite'): ?>
<a class="linkedin" href="https://www.linkedin.com/shareArticle?mini=true&url=<?php echo urlencode($base_url . '/' . $request_path); ?>" target="_blank" title="Partager sur LinkedIn"><span>LinkedIn</span></a>
<?php else: ?>
<?php head('javascript', 'https://platform.linkedin.com/in.js'); ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script type="text/javascript">
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<script type="in/share" data-counter="top" data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>"><\/script>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<script type="in/share" data-counter="right" data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>"><\/script>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
<?php endif; ?>
