<?php

/**
 *
 * @copyright  2013-2023 izend.org
 * @version    9
 * @link       http://www.izend.org
 */
?>
<div id="linkbar" class="noprint">
<a href="https://www.facebook.com/" title="Rejoignez-nous sur Facebook"><span class="icon_facebook">Facebook</span></a>
<?php if (false): ?>
<a href="https://twitter.com/" title="Suivez-nous sur Twitter"><span class="icon_twitter">Twitter</span></a>
<?php endif; ?>
<a href="https://twitter.com/" title="Suivez-nous sur X"><span class="icon_x_twitter">X</span></a>
<?php if (false): ?>
<a href="https://www.buzzmii.com/" title="Visitez notre page sur BuZZmii"><span class="icon_buzzmii">BuZZmii</span></a>
<?php endif; ?>
<a href="https://www.youtube.com/channel/" title="Visionnez nos vidéos sur YouTube"><span class="icon_youtube">YouTube</span></a>
<a href="https://www.pinterest.com/" title="Regardez nos épingles sur Pinterest"><span class="icon_pinterest">Pinterest</span></a>
<a href="https://www.instagram.com/" title="Venez-nous voir sur Instagram"><span class="icon_instagram">Instagram</span></a>
<a href="<?php echo $base_path; ?>/fr/rss" title="Inscrivez-vous au flux RSS"><span class="icon_rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/fr/infolettre/abonnement" title="Recevez notre lettre d'information"><span class="icon_newsletter">Infolettre</span></a>
</div>
