<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    7
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form action="" method="post">
<input type="hidden" name="mailme_token" value="<?php echo $token; ?>" />
<p class="inlabel<?php if ($missing_mail or $bad_mail): ?> inerror<?php endif; ?>">Quelle est votre adresse d'email&nbsp;?</p>
<p><input type="text" name="mailme_mail" id="mailme_mail" size="50" maxlength="100" title="Email" onkeypress="return focusonenter(event, 'mailme_subject')" value="<?php echo $mail; ?>" /></p>
<p class="info">Votre adresse d'email est strictement confidentielle.</p>
<p class="inlabel<?php if ($missing_subject or $bad_subject or $missing_message): ?> inerror<?php endif; ?>">Tapez le sujet et le texte de votre message&nbsp;:</p>
<p><input type="text" name="mailme_subject" id="mailme_subject" size="60" maxlength="100" title="Sujet" onkeypress="return focusonenter(event, 'mailme_message')" value="<?php echo $subject; ?>" /></p>
<p><textarea name="mailme_message" id="mailme_message" cols="70" rows="6" title="Texte"><?php echo $message; ?></textarea><br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" /></p>
<?php if ($with_appointment): ?>
<p><span class="inlabel<?php if ($bad_date): ?> inerror<?php endif; ?>">Proposez un rendez-vous&nbsp;:</span>
<input type="text" name="mailme_date" id="mailme_date" title="aaaa-mm-jj" onkeypress="return focusonenter(event, 'mailme_code')" value="<?php echo $date; ?>" /><p>
<?php endif; ?>
<?php if ($with_captcha): ?>
<p>
<img class="captcha" src="<?php echo $base_path; ?>/captcha/mailme" alt="" title="Code de vérification" />
&nbsp;:&nbsp;
<input type="text" name="mailme_code" id="mailme_code" size="4" maxlength="4" title="4 lettres" onkeypress="return submitonenter(event, 'mailme_send')" value="" />
</p>
<?php endif; ?>
<p><input type="submit" name="mailme_send" id="mailme_send" value="Envoyer" /></p>
</form>
<div class="errors">
<?php if ($missing_code): ?>
<p>Entrez le code de vérification affiché dans l'image.</p>
<?php elseif ($bad_code): ?>
<p>Le code de vérification est incorrect.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.</p>
<?php endif; ?>
</div>
<?php if ($infos): extract($infos); ?>
<div class="infos">
<?php if ($email_sent): ?>
<p>Votre message a bien été envoyé. Pour revenir à la page d'accueil, <a href="<?php echo $home_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($with_appointment): ?>
<?php head('javascript', 'jquery-ui'); ?>
<?php head('javascript', 'jquery.ui.datepicker-fr'); ?>
<?php head('stylesheet', 'jquery-ui', 'screen'); ?>
<script>
$(document).ready(function() {
    $('#mailme_date').datepicker({dateFormat: 'yy-mm-dd', autoSize: true, showAnim: 'drop', showOn: 'both', buttonText: 'Calendrier', buttonImage: '/images/theme/edit/calendar.png', buttonImageOnly: true, minDate: '+1d', maxDate: '+2m', showOtherMonths: true, navigationAsDateFormat: true, prevText: 'MM', nextText: 'MM', beforeShowDay: function(date) {return [date.getDay() != 0];}});
});
</script>
<?php endif; ?>
<script type="text/javascript">
$(document).ready(function() {
	$('.grippie').each(function() {
		var grippie = $(this);
		var textarea = grippie.prev().prev();
		var offset;

		grippie.mousedown(startDrag);

	    function startDrag(e) {
	      offset = textarea.height() - e.pageY;
	      textarea.css('opacity', 0.25);
	      $(document).mousemove(performDrag).mouseup(endDrag);
	      return false;
	    }

	    function performDrag(e) {
	      textarea.height(Math.max(32, offset + e.pageY) + 'px');
	      return false;
	    }

	    function endDrag(e) {
	      $(document).unbind('mousemove', performDrag).unbind('mouseup', endDrag);
	      textarea.css('opacity', 1);
	    }
	});
});
</script>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#mailme_code';
}
else if ($missing_mail or $bad_mail) {
	$focus='#mailme_mail';
}
else if ($missing_subject or $bad_subject) {
	$focus='#mailme_subject';
}
else if ($missing_message) {
	$focus='#mailme_message';
}
else if ($bad_date) {
	$focus='#mailme_date';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
