<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<?php require_once 'datefr.php'; ?>
<?php require_once 'bbcode.php'; ?>
<?php $message_maxlength = 2000; ?>
<div id="newcomment">
<h6>Votre commentaire&nbsp;:</h6>
<p><img src="/avatars/<?php echo $comment_name; ?>.png" alt="" title="<?php echo $comment_name; ?>"/> <span class="date">Le <?php echo longdate_fr($comment_created); ?> à <?php echo strftime("%H:%M:%S", $comment_created); ?></span> <span class="author"> par <?php echo $comment_name; ?></span></p>
<?php if (!empty($message)): ?>
<?php echo bbcode($message); ?>
<?php endif; ?>
<form action="#newcomment" method="post">
<input type="hidden" name="newcomment_token" value="<?php echo $token; ?>" />
<div class="bbcodebar">
<img src="<?php echo $base_path; ?>/images/theme/edit/p.png" alt="[p]" title="p" onclick="tagmessage('[p]','[/p]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/b.png" alt="[b]" title="b" onclick="tagmessage('[b]','[/b]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/i.png" alt="[i]" title="i" onclick="tagmessage('[i]','[/i]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/u.png" alt="[u]" title="u" onclick="tagmessage('[u]','[/u]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/s.png" alt="[s]" title="s" onclick="tagmessage('[s]','[/s]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/quote.png" alt="[quote]" title="quote" onclick="tagmessage('[quote]','[/quote]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/pre.png" alt="[pre]" title="pre" onclick="tagmessage('[pre]','[/pre]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/br.png" alt="[br]" title="br" onclick="tagmessage('','[br]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/code.png" alt="[code]" title="code" onclick="tagmessage('[code]','[/code]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/url.png" alt="[url]" title="url" onclick="tagmessage('[url]','[/url]')"/>
<img src="<?php echo $base_path; ?>/images/theme/edit/email.png" alt="[email]" title="email" onclick="tagmessage('[email]','[/email]')"/>
<span id="newcomment_limiter"><?php echo $message_maxlength; ?></span>
</div>
<textarea id="newcomment_message" name="newcomment_message" cols="80" rows="10" title="Texte" onkeyup="return inputlimit('newcomment_message', 'newcomment_limiter', <?php echo $message_maxlength; ?>)"><?php echo htmlspecialchars($message, ENT_COMPAT, 'UTF-8'); ?></textarea><br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" />
<p id="newcomment_help">
Entrez un maximum de <b><?php echo $message_maxlength; ?></b> caractères. Améliorez la présentation de votre texte avec les balises de formatage suivantes&nbsp;:<br />
[<b>p</b>]paragraphe[/p], [<b>b</b>]<b>gras</b>[/b], [<b>i</b>]<i>italique</i>[/i], [<b>u</b>]<u>souligné</u>[/u], [<b>s</b>]<s>barré</s>[/s],
[<b>quote</b>]citation[/quote], [<b>pre</b>]tel quel[/pre], [<b>br</b>]à la ligne,<br />
[<b>url</b>]http://www.izend.org[/url], [<b>url</b>=http://www.izend.org]site[/url],
[<b>email</b>]izend@izend.org[/email], [<b>email</b>=izend@izend.org]izend[/email],<br />
[<b>code</b>=langage]code source en c, java, php, html, javascript, xml, css, sql, bash, dos, make, etc.[/code].
</p>
<p>
<?php if ($message): ?>
<button type="submit" name="newcomment_edit" id="newcomment_edit">Éditer</button>
le texte ou le
<button type="submit" name="newcomment_validate" id="newcomment_validate">Valider</button>
<?php else: ?>
<button type="submit" name="newcomment_comment" id="newcomment_submit">Commenter</button>
<?php endif; ?>
</p>
</form>
<?php
if ($errors):
extract($errors);
?>
<div class="error">
<?php if ($missing_message): ?>
<p>Le message est vide.</p>
<?php elseif ($message_too_long): ?>
<p>Votre message est trop long.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
</div>
<?php endif; ?>
</div>
<script type="text/javascript">
<!--
function tagmessage(open, close)
{
	addtag('newcomment_message', open, close);
	inputlimit('newcomment_message', 'newcomment_limiter', <?php echo $message_maxlength; ?>);
}

inputlimit('newcomment_message', 'newcomment_limiter', <?php echo $message_maxlength; ?>);
//-->
</script>
<script type="text/javascript">
<!--
$(document).ready(function() {
	$('.grippie').each(function() {
		var grippie = $(this);
		var textarea = grippie.prev().prev();
		var offset;

		grippie.mousedown(startDrag);

	    function startDrag(e) {
	      offset = textarea.height() - e.pageY;
	      textarea.css('opacity', 0.25);
	      $(document).mousemove(performDrag).mouseup(endDrag);
	      return false;
	    }

	    function performDrag(e) {
	      textarea.height(Math.max(32, offset + e.pageY) + 'px');
	      return false;
	    }

	    function endDrag(e) {
	      $(document).unbind('mousemove', performDrag).unbind('mouseup', endDrag);
	      textarea.css('opacity', 1);
	    }
	});
});
//-->
</script>
