<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3><?php echo $node_title; ?></h3>
<p class="info"><?php setlocale(LC_TIME, 'fr_FR.UTF-8'); echo strftime('%e %B %Y %Hh%M', $node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Extrait</h5>
<p><?php echo $node_abstract; ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Nuage</h6>
<p class="smaller"><?php echo $node_cloud; ?></p>
<?php endif; ?>
<?php if ($node_contents): ?>
<h4>Contenu</h4>
<?php echo $node_contents; ?>
<?php endif; ?>
