<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    6
 * @link       http://www.izend.org
 */
?>
<?php require_once 'datefr.php'; ?>
<h3><?php echo htmlspecialchars($node_title ? $node_title : $node_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<p class="info"><?php echo longdatetime_fr($node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Extrait</h5>
<p><?php echo htmlspecialchars($node_abstract, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Nuage</h6>
<p class="small"><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_comment or $node_morecomment or $node_vote or $node_morevote or $node_ilike or $node_tweet or $node_plusone): ?>
<fieldset id="node_options">
<legend>Options</legend>
<div class="hbar">
<?php if ($node_comment): ?><span class="btn_edit btn_comment">commenter</span><?php endif; ?>
<?php if ($node_morecomment): ?><span class="btn_edit btn_morecomment">commenter+</span><?php endif; ?>
<?php if ($node_vote): ?><span class="btn_edit btn_vote">voter</span><?php endif; ?>
<?php if ($node_morevote): ?><span class="btn_edit btn_morevote">voter+</span><?php endif; ?>
<?php if ($node_ilike): ?><span class="btn_edit btn_ilike">facebook</span><?php endif; ?>
<?php if ($node_tweet): ?><span class="btn_edit btn_tweet">twitter</span><?php endif; ?>
<?php if ($node_plusone): ?><span class="btn_edit btn_plusone">google+</span><?php endif; ?>
<?php if ($node_linkedin): ?><span class="btn_edit btn_linkedin">linkedin</span><?php endif; ?>
</div>
</fieldset>
<?php endif; ?>
<?php if ($node_contents): ?>
<h4>Contenu</h4>
<?php echo $node_contents; ?>
<?php endif; ?>
