<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<?php require_once 'datefr.php'; ?>
<h3><?php echo htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8'); ?></h3>
<p class="info"><?php echo longdatetime_fr($node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Extrait</h5>
<p><?php echo htmlspecialchars($node_abstract, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Nuage</h6>
<p class="smaller"><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_contents): ?>
<h4>Contenu</h4>
<?php echo $node_contents; ?>
<?php endif; ?>
