<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3>Paiement rejeté</h3>
<p>Votre paiment a été rejeté. Merci d'essayer de nouveau en vérifiant vos détails de paiement.
<?php if (!empty($contact_page)): ?>Si vous pensez qu'il s'agit d'une erreur du serveur, merci de <a href="<?php echo $contact_page; ?>">nous contacter</a>.<?php endif; ?></p>
