<?php

/**
 *
 * @copyright  2010-2019 izend.org
 * @version    9
 * @link       http://www.izend.org
 */
?>
<?php switch ($mode): ?>
<?php case 'lite': ?>
<a href="https://plus.google.com/share?url=<?php echo urlencode($base_url . '/' . $request_path); ?>" target="_blank" title="Partager sur Google+"><span>Google+</span></a>
<?php break; ?>
<?php case 'awesome': ?>
<a href="https://plus.google.com/share?url=<?php echo urlencode($base_url . '/' . $request_path); ?>" target="_blank" title="Partager sur Google+"><i class="fab fa-google-plus-g"></i></a>
<?php break; ?>
<?php default: ?>
<?php head('javascript', 'https://apis.google.com/js/plusone.js', "{lang: 'fr'}"); ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script>
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<div class="g-plusone" data-href="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-size="tall" data-annotation="bubble"></div>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<div class="g-plusone" data-href="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-size="medium"></div>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
<?php break; ?>
<?php endswitch; ?>
