<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<div class="form">
<form action="" method="post">
<input type="hidden" name="profile_token" value="<?php echo $token; ?>" />
<div class="fields">
<p class="label">Nom de connexion&nbsp;:</p>
<p class="input"><input type="text" name="profile_name" id="profile_name" size="20" maxlength="20" title="Identifiant" onkeypress="return focusonenter(event, 'profile_password')" value="<?php echo $name; ?>" /><?php if (!empty($name)): ?>&nbsp;<img class="avatar" src="<?php echo $base_path; ?>/avatars/<?php echo $name; ?>.png" title="<?php echo $name; ?>" /><?php endif; ?></p>
<p class="label">Adresse d'email&nbsp;:</p>
<p class="input"><input type="text" name="profile_mail" id="profile_mail" size="50" maxlength="100" title="Email" onkeypress="return focusonenter(event, 'profile_password')" value="<?php echo $mail; ?>" /></p>
<p class="label">Langue&nbsp;:&nbsp;<?php foreach ($system_languages as $lang): ?> <input name="profile_locale" id="profile_locale" type="radio" value="<?php echo $lang; ?>" <?php if ($lang == $locale) echo 'checked="checked"'; ?> /> <?php echo $lang; ?><?php endforeach; ?></p>
<p class="label">Clé d'accès&nbsp;:</p>
<p class="input"><input type="password" name="profile_newpassword" id="profile_newpassword" size="20" maxlength="20" title="Mot de passe" onkeypress="return focusonenter(event, 'profile_password')" value="<?php echo $newpassword; ?>" /></p>
<p class="input"><button type="submit" name="profile_change" id="profile_change">Modifier</button></p>
<p class="label">Votre mot de passe actuel&nbsp;:</p>
<p class="input"><input type="password" name="profile_password" id="profile_password" size="20" maxlength="20" title="Mot de passe" onkeypress="return submitonenter(event, 'profile_change')" value="<?php echo $password; ?>" /></p>
</div>
</form>
<?php
if ($errors):
extract($errors);
?>
<div class="errors">
<?php if ($bad_name): ?>
<p>Un identifiant doit comporter entre 2 et 20 lettres.</p>
<?php endif; ?>
<?php if ($bad_mail): ?>
<p>L'adresse d'email est invalide.</p>
<?php endif; ?>
<?php if ($bad_locale): ?>
<p>La langue sélectionnée n'est pas supportée.</p>
<?php endif; ?>
<?php if ($duplicate_name): ?>
<p>Cet identifiant est déjà pris.</p>
<?php endif; ?>
<?php if ($duplicate_mail): ?>
<p>Cette adresse d'email est déjà utilisée.</p>
<?php endif; ?>
<?php if ($weak_password): ?>
<p>Entrez un mot de passe avec un minimum de 6 lettres et chiffres et avec au moins une lettre et un chiffre.</p>
<?php endif; ?>
<?php if ($missing_password): ?>
<p>Vous n'avez pas entré votre mot de passe.</p>
<?php elseif ($wrong_password): ?>
<p>Le mot de passe est erroné.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($infos):
extract($infos);
?>
<div class="infos">
<?php if ($profile_changed): ?>
<p>Vos informations personnelles ont bien été modifiées.</p>
<?php endif; ?>
<?php if ($password_changed): ?>
<p>Votre nouveau mot de passe a été enregistré.</p>
<?php endif; ?>
<?php if ($profile_changed or $password_changed): ?>
<p>Pour revenir à l'accueil, <a href="<?php echo $home_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
</div>
<?php endif; ?>
</div>
<?php if (isset($focus) and $focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>

