<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    8
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form action="" method="post">
<input type="hidden" name="register_token" value="<?php echo $token; ?>" />
<?php if ($with_name): ?>
<p class="inlabel<?php if ($missing_name or $bad_name or $duplicated_name): ?> inerror<?php endif; ?>">Quel nom de connexion voulez-vous&nbsp;?</p>
<p><input type="text" name="register_name" id="register_name" size="20" maxlength="20" title="Identifiant" onkeypress="return focusonenter(event, 'register_mail')" value="<?php echo htmlspecialchars($name, ENT_COMPAT, 'UTF-8'); ?>" /><?php if (!$missing_name and !$bad_name): ?>&nbsp;<img src="<?php echo $base_path; ?>/avatars/<?php echo $name; ?>.png" title="<?php echo $name; ?>" /><?php endif; ?></p>
<p class="info">Choisissez un pseudo de 2 à 20 lettres.</p>
<?php endif; ?>
<p class="inlabel<?php if ($missing_mail or $bad_mail or $duplicated_mail): ?> inerror<?php endif; ?>">Quelle est votre adresse d'email&nbsp;?</p>
<p><input type="text" name="register_mail" id="register_mail" size="40" maxlength="100" title="Email" onkeypress="return focusonenter(event, '<?php echo $with_password ? 'register_password' : 'register_code'; ?>')" value="<?php echo htmlspecialchars($mail, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<p class="info">Votre mot de passe sera envoyé à cette adresse.</p>
<?php if ($with_password): ?>
<p class="inlabel<?php if ($missing_password or $bad_password): ?> inerror<?php endif; ?>">Choisissez un mot de passe&nbsp;:</p>
<p><input type="text" name="register_password" id="register_password" size="20" maxlength="20" title="Mot de passe" onkeypress="return focusonenter(event, 'register_code')" value="<?php echo htmlspecialchars($password, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<p class="info">Entrez au moins 6 caractères dont 1 chiffre.</p>
<?php endif; ?>
<p><input type="checkbox" name="register_confirmed" id="register_confirmed" title="Confirmation" <?php if ($confirmed) echo 'checked="checked"'; ?> onkeypress="return focusonenter(event, 'register_code')"/>&nbsp;Je souhaite créer un compte</p>
<?php if ($with_captcha): ?>
<p>
<img src="<?php echo $base_path; ?>/captcha/register" alt="" height="40px" title="Code de vérification" />
&nbsp;:&nbsp;
<input type="text" name="register_code" id="register_code" size="4" maxlength="4" title="4 lettres" onkeypress="return submitonenter(event, 'register_register')" value="" />
</p>
<?php endif; ?>
<p><input type="submit" class="submit submit_send" name="register_register" id="register_register" value="Envoyer" /></p>
</form>
<div class="errors">
<?php if ($missing_code): ?>
<p>Entrez le code de vérification affiché dans l'image.</p>
<?php elseif ($bad_code): ?>
<p>Le code de vérification est incorrect.</p>
<?php endif; ?>
<?php if ($missing_name): ?>
<p>Vous n'avez pas saisi votre identifiant.</p>
<?php elseif ($bad_name): ?>
<p>Un identifiant doit comporter entre 2 et 20 lettres.</p>
<?php endif; ?>
<?php if ($missing_mail): ?>
<p>N'oubliez pas votre adresse d'email.</p>
<?php elseif ($bad_mail): ?>
<p>L'adresse d'email est invalide.</p>
<?php endif; ?>
<?php if ($missing_password): ?>
<p>Vous n'avez pas entré votre mot de passe.</p>
<?php elseif ($bad_password): ?>
<p>Un mot de passe doit contenir un chiffre et au moins 6 caractères.</p>
<?php endif; ?>
<?php if ($missing_confirmation): ?>
<p>Cochez la case de confirmation.</p>
<?php endif; ?>
<?php if ($duplicated_name): ?>
<p>Cet identifiant est déjà pris.</p>
<?php endif; ?>
<?php if ($duplicated_mail): ?>
<p>Cette adresse d'email est déjà utilisée.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
</div>
<?php if ($infos): extract($infos); ?>
<div class="infos">
<?php if ($account_created): ?>
<p>Votre compte a bien été créé. Le mot de passe a été envoyé par email à votre adresse.<br />
Pour vous identifier, <a href="<?php echo $user_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#register_code';
}
else if ($missing_name or $bad_name or $duplicated_name) {
	$focus='#register_name';
}
else if ($missing_mail or $bad_mail or $duplicated_mail) {
	$focus='#register_mail';
}
else if ($missing_password or $bad_password) {
	$focus='#register_password';
}
else if ($missing_confirmation) {
	$focus='#register_confirmed';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
