<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<div class="form">
<form action="" method="post">
<input type="hidden" name="register_token" value="<?php echo $token; ?>" />
<div class="fields">
<p class="label">Quel nom de connexion voulez-vous ?</p>
<p class="input"><input type="text" name="register_name" id="register_name" size="20" maxlength="20" title="Identifiant" onkeypress="return focusonenter(event, 'register_mail')" value="<?php echo $name; ?>" /><?php if (!empty($name)): ?>&nbsp;<img src="<?php echo $base_path; ?>/avatars/<?php echo $name; ?>.png" title="<?php echo $name; ?>" /><?php endif; ?></p>
<p class="info">Choisissez un pseudo de 2 à 20 lettres.</p>
<p class="label">Quelle est votre adresse d'email ?</p>
<p class="input"><input type="text" name="register_mail" id="register_mail" size="50" maxlength="100" title="Email" onkeypress="return focusonenter(event, 'register_code')" value="<?php echo $mail; ?>" /></p>
<p class="info">Votre mot de passe sera envoyé à cette adresse.</p>
<p class="label"><input type="checkbox" name="register_confirmed" id="register_confirmed" title="Confirmation" <?php if ($confirmed) echo 'checked="checked"'; ?> onkeypress="return focusonenter(event, 'register_code')"/>&nbsp;Je souhaite créer un compte</p>
<?php if ($with_captcha): ?>
<p class="input">
<img src="<?php echo $base_path; ?>/captcha/register" alt="" title="Code de vérification" />
&nbsp;:&nbsp;
<input type="text" name="register_code" id="register_code" size="4" maxlength="4" title="4 lettres" onkeypress="return submitonenter(event, 'register_register')" value="" />
</p>
<?php endif; ?>
<p class="submit"><button type="submit" name="register_register" id="register_register">Envoyer</button></p>
</div>
</form>
<?php
if ($errors):
extract($errors);
?>
<div class="errors">
<?php if ($missing_code): ?>
<p>Entrez le code de vérification affiché dans l'image.</p>
<?php elseif ($bad_code): ?>
<p>Le code de vérification est incorrect.</p>
<?php endif; ?>
<?php if ($missing_name): ?>
<p>Vous n'avez pas saisi votre identifiant.</p>
<?php elseif ($bad_name): ?>
<p>Un identifiant doit comporter entre 2 et 20 lettres.</p>
<?php endif; ?>
<?php if ($missing_mail): ?>
<p>N'oubliez pas votre adresse d'email.</p>
<?php elseif ($bad_mail): ?>
<p>L'adresse d'email est invalide.</p>
<?php endif; ?>
<?php if ($missing_confirmation): ?>
<p>Cochez la case de confirmation.</p>
<?php endif; ?>
<?php if ($duplicated_name): ?>
<p>Cet identifiant est déjà pris.</p>
<?php endif; ?>
<?php if ($duplicated_mail): ?>
<p>Cette adresse d'email est déjà utilisée.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($infos):
extract($infos);
?>
<div class="infos">
<?php if ($account_created): ?>
<p>Votre compte a bien été créé. Le mot de passe a été envoyé par email à votre adresse.<br />
Pour vous identifier, <a href="<?php echo $user_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
</div>
<?php endif; ?>
</div>
<?php if (isset($focus) and $focus): ?>
<script type="text/javascript">
<!--
$(function() {$('<?php echo $focus; ?>').focus();});
//-->
</script>
<?php endif; ?>

