<?php

/**
 *
 * @copyright  2010-2016 izend.org
 * @version    12
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form action="" method="post">
<input type="hidden" name="remindme_token" value="<?php echo $token; ?>" />
<p class="inlabel<?php if ($missing_login or $bad_login): ?> inerror<?php endif; ?>"><?php if ($with_name): ?>Quel est votre nom de connexion&nbsp;?<?php else: ?>Quelle est votre adresse d'email&nbsp;?<?php endif; ?></p>
<p><input type="text" name="remindme_login" id="remindme_login" size="40" maxlength="100" title="Identifiant" onkeypress="return focusonenter(event, 'remindme_code')" value="<?php echo htmlspecialchars($login, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<?php if ($with_name): ?>
<p class="info">Vous pouvez aussi entrer votre adresse d'email.</p>
<?php endif; ?>
<p><input name="remindme_confirmed" id="remindme_confirmed" type="checkbox" title="Confirmation" <?php if ($confirmed): ?> checked="checked" <?php endif; ?> />&nbsp;Je veux recevoir un nouveau mot de passe</p>
<?php if ($with_captcha): ?>
<p>
<img src="<?php echo $base_path; ?>/captcha/remindme" alt="" height="40" title="Code de vérification" />
:
<input type="text" name="remindme_code" id="remindme_code" size="4" maxlength="4" title="4 lettres" autocomplete="off" onkeypress="return submitonenter(event, 'remindme_send')" value="" />
</p>
<?php endif; ?>
<p><input type="submit" class="submit submit_send" name="remindme_send" id="remindme_send" value="Envoyer" /></p>
</form>
<div class="errors">
<?php if ($missing_code): ?>
<p>Entrez le code de vérification affiché dans l'image.</p>
<?php elseif ($bad_code): ?>
<p>Le code de vérification est incorrect.</p>
<?php endif; ?>
<?php if ($missing_login): ?>
<p>Vous n'avez pas saisi votre identifiant.</p>
<?php elseif ($bad_login): ?>
<p>L'identifiant n'est pas valide.</p>
<?php endif; ?>
<?php if ($missing_confirmation): ?>
<p>Cochez la case de confirmation.</p>
<?php endif; ?>
</div>
<?php extract($infos); ?>
<div class="infos">
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($email_sent): ?>
<p>Un nouveau mot de passe vous a été envoyé par email.<br />
Pour vous identifier, <a href="<?php echo $user_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
</div>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#remindme_code';
}
else if ($missing_login or $bad_login) {
	$focus='#remindme_login';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
