<?php

/**
 *
 * @copyright  2012-2023 izend.org
 * @version    16
 * @link       http://www.izend.org
 */
?>
<span id="socialbar" class="menu noprint">
<a class="facebook" href="https://www.facebook.com/pages/" title="Rejoignez-nous sur Facebook"><span>Facebook</span></a>
<?php if (false): ?>
<a class="twitter" href="https://twitter.com/#!/" title="Suivez-nous sur Twitter"><span>Twitter</span></a>
<?php endif; ?>
<a class="x_twitter" href="https://twitter.com/#!/" title="Suivez-nous sur X"><span>X</span></a>
<a class="linkedin" href="http://fr.linkedin.com/" title="Connectez-vous à notre réseau sur LinkedIn"><span>LinkedIn</span></a>
<a class="youtube" href="https://www.youtube.com/channel/" title="Visionnez nos vidéos sur YouTube"><span>YouTube</span></a>
<a class="pinterest" href="https://www.pinterest.com/" title="Regardez nos épingles sur Pinterest"><span>Pinterest</span></a>
<a class="rss" href="<?php echo $base_path; ?>/fr/rss" rel="nofollow" title="Inscrivez-vous au flux RSS"><span>RSS</span></a>
<a class="newsletter" href="<?php echo $base_path; ?>/fr/infolettre/abonnement" rel="nofollow" title="Recevez notre lettre d'information"><span>Infolettre</span></a>
<a class="email" href="<?php echo $base_path; ?>/fr/contact" rel="nofollow" title="Contactez-nous"><span>Email</span></a>
</span>
