<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<?php if ($search_input): ?>
<form id="searchinput" action="<?php echo $search_url; ?>" method="post">
<input id="searchtext" name="searchtext" type="text" />
<button id="search" name="search" type="submit" title="Chercher">Chercher</button>
</form>
<?php endif; ?>
<?php if ($summary): ?>
<ol id="storysummary">
<?php foreach ($summary as $p): ?>
<?php list($title, $url)=$p; ?>
<li><a href="<?php echo $url; ?>"><?php echo htmlspecialchars($title, ENT_NOQUOTES, 'UTF-8', false); ?></a></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
<?php if ($search_cloud): ?>
<?php echo $search_cloud; ?>
<?php endif; ?>
