<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php require_once 'datefr.php'; ?>
<h3><?php echo $thread_title; ?></h3>
<p class="info"><?php echo longdatetime_fr($thread_modified); ?></p>
<?php if ($thread_abstract): ?>
<h5>Extrait</h5>
<p><?php echo htmlspecialchars($thread_abstract, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($thread_cloud): ?>
<h6>Nuage</h6>
<p class="smaller"><?php echo $thread_cloud; ?></p>
<?php endif; ?>
<h4>Contenu</h4>
<?php if ($thread_contents): ?>
<ol>
<?php foreach ($thread_contents as $c): ?>
<?php extract($c);	/* node_title node_url */ ?>
<li><a href="<?php echo $node_url; ?>"><?php echo htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8'); ?></a></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
