<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    6
 * @link       http://www.izend.org
 */
?>
<?php require_once 'datefr.php'; ?>
<div id="threadnode">
<h3><?php echo htmlspecialchars($node_title ? $node_title : $node_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<p id="threadnodenav" class="menu">
<?php if ($prev_node_url): ?>
<a href="<?php echo $prev_node_url; ?>"><img src="/images/theme/icons/left.png" alt=""/></a>
<a href="<?php echo $prev_node_url; ?>"><?php echo htmlspecialchars($prev_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<?php endif; ?>
<?php if ($next_node_url and $prev_node_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_node_url): ?>
<a href="<?php echo $next_node_url; ?>"><?php echo htmlspecialchars($next_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<a href="<?php echo $next_node_url; ?>"><img src="/images/theme/icons/right.png" alt=""/></a>
<?php endif; ?>
</p>
<p class="info"><?php echo longdatetime_fr($node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Extrait</h5>
<p><?php echo $node_abstract; ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Nuage</h6>
<p class="small"><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_comment or $node_morecomment or $node_ilike or $node_tweet or $node_plusone): ?>
<fieldset id="node_options">
<legend>Options</legend>
<div class="hbar">
<?php if ($node_comment): ?><img src="<?php echo $base_path; ?>/images/theme/edit/comment.png" alt="" /><?php endif; ?>
<?php if ($node_morecomment): ?><img src="<?php echo $base_path; ?>/images/theme/edit/comment_add.png" alt="" /><?php endif; ?>
<?php if ($node_ilike): ?><img src="<?php echo $base_path; ?>/images/theme/edit/facebook.png" alt="" /><?php endif; ?>
<?php if ($node_tweet): ?><img src="<?php echo $base_path; ?>/images/theme/edit/twitter.png" alt="" /><?php endif; ?>
<?php if ($node_plusone): ?><img src="<?php echo $base_path; ?>/images/theme/edit/plusone.png" alt="" /><?php endif; ?>
</div>
</fieldset>
<?php endif; ?>
<?php if ($node_contents): ?>
<h4>Contenu</h4>
<div id="threadnodecontent">
<?php echo $node_contents; ?>
</div>
<?php endif; ?>
</div>
