<?php

/**
 *
 * @copyright  2010-2017 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<h3><?php echo htmlspecialchars($site_title ? $site_title : $sitename, ENT_COMPAT, 'UTF-8'); ?></h3>
<p class="compact">
<?php echo $inlanguages; ?>
</p>
<?php if ($site_abstract): ?>
<h5>Extrait</h5>
<p><?php echo htmlspecialchars($site_abstract, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($site_cloud): ?>
<h6>Nuage</h6>
<p class="small"><?php echo $site_cloud; ?></p>
<?php endif; ?>
<h4>Contenu</h4>
<?php echo $threadlist; ?>
