<?php

/**
 *
 * @copyright  2010-2017 izend.org
 * @version    14
 * @link       http://www.izend.org
 */
?>
<?php require_once 'datefr.php'; ?>
<h3><?php echo htmlspecialchars($node_title ? $node_title : $node_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<?php if ($next_node_url or $prev_node_url): ?>
<p class="navigation menu">
<?php if ($prev_node_url): ?>
<a class="previous" href="<?php echo $prev_node_url; ?>"><span>&lt;</span></a>
<a href="<?php echo $prev_node_url; ?>"><?php echo htmlspecialchars($prev_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<?php endif; ?>
<?php if ($next_node_url and $prev_node_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_node_url): ?>
<a href="<?php echo $next_node_url; ?>"><?php echo htmlspecialchars($next_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<a class="next" href="<?php echo $next_node_url; ?>"><span>&gt;</span></a>
<?php endif; ?>
</p>
<?php endif; ?>
<p class="compact">
<?php echo $inlanguages; ?>
<span id="node_hidy" class="hidy">+</span>
</p>
<div id="node">
<p class="info"><?php echo longdatetime_fr($node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Extrait</h5>
<p><?php echo $node_abstract; ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Nuage</h6>
<p class="small"><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_image): ?>
<h6>Image</h6>
<p><img id="node_image" src="<?php echo str_replace('%2F', '/', urlencode($node_image)); ?>" alt="<?php echo htmlspecialchars($node_image, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<?php endif; ?>
<?php if ($node_visits or $node_comment or $node_morecomment or $node_vote or $node_morevote or $node_ilike or $node_tweet or $node_plusone or $node_linkedin or $node_pinit): ?>
<fieldset id="node_options">
<legend>Options</legend>
<div class="hbar">
<?php if ($node_visits): ?><span class="btn_edit btn_visits">visites</span><?php endif; ?>
<?php if ($node_comment): ?><span class="btn_edit btn_comment">commenter</span><?php endif; ?>
<?php if ($node_morecomment): ?><span class="btn_edit btn_morecomment">commenter+</span><?php endif; ?>
<?php if ($node_vote): ?><span class="btn_edit btn_vote">voter</span><?php endif; ?>
<?php if ($node_morevote): ?><span class="btn_edit btn_morevote">voter+</span><?php endif; ?>
<?php if ($node_ilike): ?><span class="btn_edit btn_ilike">facebook</span><?php endif; ?>
<?php if ($node_tweet): ?><span class="btn_edit btn_tweet">twitter</span><?php endif; ?>
<?php if ($node_plusone): ?><span class="btn_edit btn_plusone">google+</span><?php endif; ?>
<?php if ($node_linkedin): ?><span class="btn_edit btn_linkedin">linkedin</span><?php endif; ?>
<?php if ($node_pinit): ?><span class="btn_edit btn_pinit">pinit</span><?php endif; ?>
</div>
</fieldset>
<?php endif; ?>
</div>
<?php if ($node_contents): ?>
<h4>Contenu</h4>
<?php echo $node_contents; ?>
<?php endif; ?>
<?php head('javascript', 'jquery.cookie'); ?>
<script type="text/javascript">
if ($.cookie('hidenode') == 1) {
	$('#node').hide();
}
$('#node_hidy').click(function() {
	$('#node').toggle();
	$.cookie('hidenode', $('#node').is(':hidden') ? 1 : 0, { path: '/' });
});
</script>
