<?php

/**
 *
 * @copyright  2010-2019 izend.org
 * @version    14
 * @link       http://www.izend.org
 */
?>
<?php switch ($mode): ?>
<?php case 'lite': ?>
<?php $uri="$base_url/$request_path"; ?>
<a href="https://twitter.com/home?status=<?php echo urlencode(!empty($tweet_text) ? "$tweet_text\n$uri" : $uri); ?>" title="Partager sur Twitter"><span>Twitter</span></a>
<?php break; ?>
<?php case 'awesome': ?>
<?php $uri="$base_url/$request_path"; ?>
<a href="https://twitter.com/home?status=<?php echo urlencode(!empty($tweet_text) ? "$tweet_text\n$uri" : $uri); ?>" title="Partager sur Twitter"><i class="fab fa-twitter"></i></a>
<?php break; ?>
<?php default: ?>
<?php head('javascript', 'https://platform.twitter.com/widgets.js'); ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script>
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<a href="https://twitter.com/share" class="twitter-share-button"<?php if (!empty($tweet_text)): ?> data-text="<?php echo htmlentities($tweet_text, ENT_QUOTES, 'UTF-8'); ?>"<?php endif; ?> data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-count="vertical" data-lang="fr"></a>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<a href="https://twitter.com/share" class="twitter-share-button"<?php if (!empty($tweet_text)): ?> data-text="<?php echo htmlentities($tweet_text, ENT_QUOTES, 'UTF-8'); ?>"<?php endif; ?> data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-count="horizontal" data-lang="fr"></a>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
<?php break; ?>
<?php endswitch; ?>
