<?php

/**
 *
 * @copyright  2012 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<form enctype="multipart/form-data" action="" method="post" class="compact">
<input type="hidden" name="upload_token" value="<?php echo $token; ?>" />
<input type="hidden" name="MAX_FILE_SIZE" value="1000000" />
<p><input type="file" name="upload_file" id="upload_file" size="40"/></p>
<p><input type="submit" class="submit submit_put" id="upload_put" name="upload_put" value="Télécharger"/>
<?php extract($errors); ?>
<?php if ($missing_file or $bad_file or $bad_name or $bad_size or $bad_file or $bad_copy or $copy_error): ?>
<img src="/images/theme/icons/no.png" alt=""/>
<?php endif; ?>
<?php extract($infos); ?>
<?php if ($file_copied): ?>
<img src="/images/theme/icons/yes.png" alt=""/>
<?php endif; ?>
</p>
</form>
<script type="text/javascript">
$(function() {
    var file=$('#upload_file');
    var upload=$('#upload_put');

    file.hide().change(function() {if (file.val()) {upload.unbind('click').click();}});
    upload.click(function(event) {event.preventDefault();file.click();});
});
</script>
