<?php

/**
 *
 * @copyright  2022 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form method="post">
<input type="hidden" name="userpassword_token" value="<?php echo $token; ?>" />
<?php if ($with_oldpassword): ?>
<p class="noprint inlabel<?php if ($missing_oldpassword or $bad_oldpassword): ?> inerror<?php endif; ?>">Mot de passe actuel&nbsp;:</p>
<p class="noprint"><input type="password" name="userpassword_oldpassword" id="userpassword_oldpassword" size="20" maxlength="20" title="au moins 6 lettres et chiffres" onkeypress="return focusonenter(event, 'userpassword_newpassword')" /><?php if ($with_viewpassword): ?>&nbsp;<span class="icon icon_view pointer"></span><?php endif; ?></p>
<?php endif; ?>
<p class="noprint inlabel<?php if ($missing_newpassword or $bad_newpassword): ?> inerror<?php endif; ?>">Nouveau mot de passe&nbsp;:</p>
<p class="noprint"><input type="text" name="userpassword_newpassword" id="userpassword_newpassword" size="20" maxlength="20" title="au moins 6 lettres et chiffres" onkeypress="return submitonenter(event, 'userpassword_change')" autocomplete="off" value="<?php echo htmlspecialchars($newpassword, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<p class="noprint"><input type="submit" class="submit submit_change" name="userpassword_change" id="userpassword_change" value="Changer" /></p>
</form>
<?php if ($with_oldpassword and $with_viewpassword): ?>
<script>
(function() {
	const password = document.getElementById('userpassword_oldpassword');
	password.nextElementSibling.addEventListener('click', () => password.type = password.type == 'password' ? 'text' : 'password');
})();
</script>
<?php endif; ?>
<div class="errors">
<?php if ($missing_oldpassword or $bad_oldpassword): ?>
<p>Accès refusé.</p>
<?php elseif ($missing_newpassword or $bad_newpassword): ?>
<p>Entrez une combinaison de lettres et de chiffres d'au moins 6 caractères.</p>
<?php endif; ?>
</div>
<?php extract($infos); ?>
<div class="infos">
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($password_changed): ?>
<p>Le mot de passe a été changé.
Pour vous identifier, <a class="clickhere" href="<?php echo $user_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
</div>
<?php
$focus=false;
if ($missing_oldpassword or $bad_oldpassword) {
	$focus='#userpassword_oldpassword';
}
else if ($missing_newpassword or $bad_newpassword) {
	$focus=$with_oldpassword ? '#userpassword_oldpassword' : '#userpassword_newpassword';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
