<?php

/**
 *
 * @copyright  2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<form action="" method="post">
<input type="hidden" name="useredit_token" value="<?php echo $token; ?>" />
<?php if ($user_accessed): ?>
<input type="hidden" name="useredit_accessed" value="<?php echo $user_accessed; ?>" />
<?php endif; ?>
<p>Nom de connexion&nbsp;:</p>
<p><input type="text" name="useredit_name" id="useredit_name" size="20" maxlength="20" title="2 à 20 lettres" onkeypress="return submitonenter(event, 'useredit_modify')" value="<?php echo htmlspecialchars($user_name, ENT_COMPAT, 'UTF-8'); ?>" /><?php if (!empty($user_name)): ?>&nbsp;<img class="avatar" src="<?php echo $base_path; ?>/avatars/<?php echo $user_name; ?>.png" /><?php endif; ?></p>
<p>Adresse d'email&nbsp;:</p>
<p><input type="text" name="useredit_mail" id="useredit_mail" size="40" maxlength="100" title="nom@domaine.fr" onkeypress="return submitonenter(event, 'useredit_modify')" value="<?php echo htmlspecialchars($user_mail, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<p>Site web&nbsp;:</p>
<p><input type="text" name="useredit_website" id="useredit_website" size="40" maxlength="100" title="www.domaine.fr" onkeypress="return submitonenter(event, 'useredit_modify')" value="<?php echo htmlspecialchars($user_website, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<p><?php foreach ($system_languages as $lang): ?> <input name="useredit_locale" id="useredit_locale" type="radio" value="<?php echo $lang; ?>" <?php if ($lang == $user_locale) echo 'checked="checked"'; ?> /> <?php echo $lang; ?><?php endforeach; ?></p>
<?php if ($with_status): ?>
<fieldset id="useredit_status">
<legend>Statut</legend>
<input name="useredit_active" type="checkbox" <?php if ($user_active) echo 'checked="checked"'; ?> />&nbsp;actif
<input name="useredit_banned" type="checkbox" <?php if ($user_banned) echo 'checked="checked"'; ?> />&nbsp;banni
</fieldset>
<?php if ($user_accessed): ?>
<?php require_once 'datefr.php'; ?>
<p><span id="useredit_accessed">Dernier accès le <?php echo longdate_fr($user_accessed); ?> à <?php echo date('H:i', $user_accessed); ?></span></p>
<?php endif; ?>
<p>
<?php endif; ?>
<?php if ($with_delete): ?>
<?php if ($confirm_delete): ?>
<button type="submit" name="useredit_confirmdelete" id="useredit_confirmdelete">Confirmer</button>
la suppression ou
<button type="submit" name="useredit_cancel" id="useredit_cancel">Annuler</button>
<?php else: ?>
<button type="submit" name="useredit_modify" id="useredit_modify">Modifier</button>
le profil ou
<button type="submit" name="useredit_delete" id="useredit_delete">Supprimer</button>
le compte
<?php endif; ?>
<?php else: ?>
<button type="submit" name="useredit_modify" id="useredit_modify">Modifier</button>
<?php endif; ?>
</p>
</form>
<?php extract($errors); ?>
<?php if ($missing_name): ?>
<p class="error">Un identifiant est obligatoire.</p>
<?php elseif ($bad_name): ?>
<p class="error">Un identifiant doit comporter de 2 à 20 lettres.</p>
<?php elseif ($duplicated_name): ?>
<p class="error">Cet identifiant est déjà pris.</p>
<?php endif; ?>
<?php if ($missing_mail): ?>
<p class="error">Une adresse d'email est obligatoire.</p>
<?php elseif ($bad_mail): ?>
<p class="error">L'adresse d'email est invalide.</p>
<?php elseif ($duplicated_mail): ?>
<p class="error">Cette adresse d'email est déjà utilisée.</p>
<?php endif; ?>
<?php if ($bad_website): ?>
<p class="error">L'URL du site web est invalide.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p class="error">Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
<?php extract($infos); ?>
<?php if ($account_modified): ?>
<p>Les données du compte ont été modifiées.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_name or $bad_name or $duplicated_name) {
	$focus='#useredit_name';
}
else if ($missing_mail or $bad_mail or $duplicated_mail) {
	$focus='#useredit_mail';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
