<?php

/**
 *
 * @copyright  2012 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<?php if ($vote_total > 0 or !$nomore): ?>
<?php if (!$nomore): ?>
<form action="" method="post">
<?php endif; ?>
<p class="vote" >
<?php if ($vote_total > 0): ?>
<?php require_once 'countformat.php'; ?>
<span class="count" title="<?php echo number_format($vote_total, 0, ',', ' '); ?> recommandation<?php if ($vote_total > 1): ?>s<?php endif; ?>"><?php echo count_format($vote_total, ',', ' '); ?></span>
<?php endif; ?>
<?php if ($nomore): ?>
<span class="plusone"></span>
<?php else: ?>
<input type="submit" class="plusone" name="vote_plusone" value="+1" title="Recommander" />
<?php endif; ?>
</p>
<?php if (!$nomore): ?>
</form>
<?php endif; ?>
<?php endif; ?>
