<?php

/**
 *
 * @copyright  2012-2014 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<form action="" method="post" class="compact noprint">
<p class="balance">
<input type="submit" class="submit submit_paypal" name="balance_balance" id="balance_balance" value="Balance" title="Balance"/>
<?php if ($balance): ?>
<span><?php echo number_format($balance, 2, '.', ' '); ?>&nbsp;<?php echo $currency; ?></span>
<?php endif; ?>
</p>
</form>
