<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    5
 * @link       http://www.izend.org
 */
?>
<div id="bannermenu">
<?php if (!empty($contact_page) or !empty($user_page) or !empty($nobody_page) or !empty($account_page) or !empty($edit_page) or !empty($view_page) or !empty($validate_page) or !empty($admin_page)): ?>
<ul class="menu menubar">
<?php if (!empty($contact_page)): ?>
<li><a class="btn_mail" href="<?php echo $contact_page; ?>" rel="nofollow" title="Contact us"><span>Contact</span></a></li>
<?php endif; ?>
<?php if (!empty($user_page)): ?>
<li><a class="btn_login" href="<?php echo $user_page; ?>" rel="nofollow" title="Your account"><span>Account</span></a></li>
<?php endif; ?>
<?php if (!empty($nobody_page)): ?>
<li><a class="btn_logout" href="<?php echo $nobody_page; ?>" rel="nofollow" title="Disconnect"><span>Disconnect</span></a></li>
<?php endif; ?>
<?php if (!empty($account_page)): ?>
<li><a class="btn_account" href="<?php echo $account_page; ?>" rel="nofollow" title="Your account"><span>Account</span></a></li>
<?php endif; ?>
<?php if (!empty($edit_page)): ?>
<li><a class="btn_edit" href="<?php echo $edit_page; ?>" title="Edit" rel="nofollow"><span>Edit</span></a></li>
<?php elseif ($view_page): ?>
<li><a class="btn_view" href="<?php echo $view_page; ?>" title="View" rel="nofollow"><span>View</span></a></li>
<?php endif; ?>
<?php if (!empty($validate_page)): ?>
<li><a class="btn_validate" href="http://validator.w3.org/check?uri=<?php echo $base_url . $validate_page; ?>" target="validator.w3.org" rel="nofollow" title="Validate"><span>Validate</span></a></li>
<?php endif; ?>
<?php if (!empty($admin_page)): ?>
<li><a class="btn_admin" href="<?php echo $admin_page; ?>" rel="nofollow" title="Manage"><span>Manage</span></a></li>
<?php endif; ?>
</ul>
<?php endif; ?>
</div>
