<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3><?php echo $page_title; ?></h3>
<p id="bookpagenav" class="menubar">
<?php if ($prev_page_url): ?>
<a href="<?php echo $prev_page_url; ?>" title="Previous page"><?php echo $prev_page_label; ?></a>
<?php endif; ?>
<?php if ($next_page_url and $prev_page_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_page_url): ?>
<a href="<?php echo $next_page_url; ?>" title="Next page"><?php echo $next_page_label; ?></a>
<?php endif; ?>
</p>
<?php if ($page_contents): ?>
<?php echo $page_contents; ?>
<?php endif; ?>
<?php if ($page_comment): ?>
<?php echo $page_comment; ?>
<?php endif; ?>
