<?php

/**
 *
 * @copyright  2017 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3>New account</h3>
<?php extract($errors); ?>
<?php if ($bad_user): ?>
<p>This user is not registered.</p>
<?php elseif ($bad_time): ?>
<p>The authorized delay for this operation is expired.
A new link has been sent to your address.</p>
<?php endif; ?>
<?php extract($infos); ?>
<div class="infos">
<?php if ($internal_error): ?>
<p>An internal error has occurred.
<?php if ($contact_page): ?>If you can describe the problem, please <a href="<?php echo $contact_page; ?>" rel="nofollow">contact us</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($account_confirmed): ?>
<p>Your account has been validated.
To identify yourself, <a href="<?php echo $user_page; ?>">click here</a>.</p>
<?php endif; ?>
</div>