<?php

/**
 *
 * @copyright  2014 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3>Newsletter</h3>
<?php extract($errors); ?>
<?php if ($bad_mail): ?>
<p>The email address <i><?php echo $mail; ?></i> is not registered.</p>
<?php elseif ($bad_time): ?>
<p>The authorized delay for this operation is expired.</p>
<?php else: ?>
<p>The email address <i><?php echo $mail; ?></i> has been unregistered.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>An internal error has occurred.
<?php if ($contact_page): ?>If you can describe the problem, please <a href="<?php echo $contact_page; ?>" rel="nofollow">contact us</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($subscribe_page): ?>
<p>To receive the newsletter, <a href="<?php echo $subscribe_page; ?>">click here</a>.</p>
<?php endif; ?>
<?php if ($unsubscribe_page): ?>
<p>To stop receiving the newsletter, <a href="<?php echo $unsubscribe_page; ?>">click here</a>.</p>
<?php endif; ?>
