<?php

/**
 *
 * @copyright  2016-2020 izend.org
 * @version    6
 * @link       http://www.izend.org
 */
?>
<div id="consent">
<p>By using this website, <b>you are accepting the use of cookies</b> in accordance with our personal data policy.
<?php if (true): ?>
<b>Note</b> that cookies from this website are exempt from obtaining consent because
<i>strickly necessary to provide a service at the user’s request</i>.
<?php endif; ?>
<?php if (false): ?>
<p>To learn more, <a class="clickhere" href="/en/legal-information" title="Legal information">click here</a>.
<?php endif; ?>
</p>
<?php if ($confirmcookieconsent): ?>
<p><span id="consentyes" class="clickit">I get it</span></p>
<?php endif; ?>
</div>
<?php if ($confirmcookieconsent): ?>
<?php head('javascript', 'js.cookie'); ?>
<script>
$('#consentyes').click(function() {
	Cookies.set('cookieconsent', 1, { path: '/', sameSite: 'lax' });
	$('#consent').hide();
});
</script>
<?php endif; ?>
