<?php

/**
 *
 * @copyright  2016 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<div id="consent">
<p>By using this website, <b>you are accepting the use of cookies</b> in accordance with our personal data policy.
<b>Note</b> that cookies from this website are exempt from obtaining consent because
<i>strickly necessary to provide a service at the user’s request</i>.</p>
<?php if (false): ?>
<p>To learn more, <a href="#">click here</a>.</p>
<?php endif; ?>
</div>
