<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3>Donation</h3>
<p class="vignette"><img src="<?php echo $base_path; ?>/images/paypal_solutions.png" alt="" title="PayPal - The safer, easier way to pay online!"/></p>
<p>Please show your appreciation of the work presented by this site by contributing to its development with a donation.</p>
<?php echo $donateme; ?>
