<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<div id="footer">
<p>&copy;&nbsp;<?php echo idate('Y'); ?> <?php echo $sitename; ?> &bull; <a href="<?php echo $base_path; ?>/en/legal-information" rel="nofollow">Legal information</a><?php if ($contact_page): ?> &bull; <a href="<?php echo $contact_page; ?>">Contact</a><?php endif; ?></p>
</div>
