<?php

/**
 *
 * @copyright  2013 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<div id="linkbar" class="noprint">
<a href="https://www.facebook.com/" target="_blank" title="Join us on Facebook"><span class="icon_facebook">Facebook</a>
<a href="https:/twitter.com/" target="_blank" title="Follow us on Twitter"><span class="icon_twitter">Twitter</a>
<a href="<?php echo $base_path; ?>/en/rss" title="Subscribe to the RSS feed"><span class="icon_rss">RSS</a>
<a href="<?php echo $base_path; ?>/en/newsletter/subscribe" title="Receive our newsletter"><span class="icon_newsletter">Newsletter</a>
</div>
