<?php

/**
 *
 * @copyright  2013-2023 izend.org
 * @version    9
 * @link       http://www.izend.org
 */
?>
<div id="linkbar" class="noprint">
<a href="https://www.facebook.com/" title="Join us on Facebook"><span class="icon_facebook">Facebook</span></a>
<?php if (false): ?>
<a href="https://twitter.com/" title="Follow us on Twitter"><span class="icon_twitter">Twitter</span></a>
<?php endif; ?>
<a href="https://twitter.com/" title="Follow us on X"><span class="icon_x_twitter">X</span></a>
<?php if (false): ?>
<a href="https://www.buzzmii.com/" title="Visit our page on BuZZmii"><span class="icon_buzzmii">BuZZmii</span></a>
<?php endif; ?>
<a href="https://www.youtube.com/channel/" title="Watch our videos on YouTube"><span class="icon_youtube">YouTube</span></a>
<a href="https://www.pinterest.com/" title="Look at our pins on Pinterest"><span class="icon_pinterest">Pinterest</span></a>
<a href="https://www.instagram.com/" title="See us on Instagram"><span class="icon_instagram">Instagram</span></a>
<a href="<?php echo $base_path; ?>/en/rss" title="Subscribe to the RSS feed"><span class="icon_rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/en/newsletter/subscribe" title="Receive our newsletter"><span class="icon_newsletter">Newsletter</span></a>
</div>
