<?php

/**
 *
 * @copyright  2010-2016 izend.org
 * @version    9
 * @link       http://www.izend.org
 */
?>
<?php switch ($mode): ?>
<?php case 'lite': ?>
<a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo urlencode($base_url . '/' . $request_path); ?>" target="_blank" title="Share on LinkedIn"><span>LinkedIn</span></a>
<?php break; ?>
<?php case 'awesome': ?>
<a href="https://www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo urlencode($base_url . '/' . $request_path); ?>" target="_blank" title="Share on LinkedIn"><i class="fa fa-linkedin"></i></a>
<?php break; ?>
<?php default: ?>
<?php head('javascript', 'https://platform.linkedin.com/in.js', 'lang: en_US'); ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script type="text/javascript">
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<script type="in/share" data-counter="top" data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>"><\/script>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<script type="in/share" data-counter="right" data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>"><\/script>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
<?php endswitch; ?>
