<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<?php head('javascript', 'https://platform.linkedin.com/in.js', 'screen'); ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script type="text/javascript">
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<script type="in/share" data-counter="top" data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>"><\/script>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<script type="in/share" data-counter="right" data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>"><\/script>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
