<?php

/**
 *
 * @copyright  2010-2023 izend.org
 * @version    18
 * @link       http://www.izend.org
 */
?>
<?php if ($with_google): ?>
<?php global $googleclientid; ?>
<script async defer src="https://accounts.google.com/gsi/client"></script>
<div id="g_id_onload" data-client_id="<?php echo $googleclientid; ?>" data-context="signin" data-ux_mode="redirect" data-login_uri="<?php echo $base_url; ?><?php echo $user_page; ?>" data-auto_prompt="false" data-auto_select="true" data-itp_support="true"></div>
<?php endif; ?>
<?php extract($errors); ?>
<form method="post">
<input type="hidden" name="login_token" value="<?php echo $token; ?>" />
<p class="inlabel<?php if ($missing_login or $bad_login): ?> inerror<?php endif; ?>"><?php if ($with_name): ?>What is your connection name?<?php else: ?>What is your email address?<?php endif; ?></p>
<p><input type="text" name="login_login" id="login_login" size="30" maxlength="100" title="<?php if ($with_name): ?>Identifier<?php else: ?>name@domain.net<?php endif; ?>" onkeypress="return focusonenter(event, 'login_password')" value="<?php if ($login): ?><?php echo htmlspecialchars($login, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" />
<?php if ($with_google): ?>
<span id="connectbar" class="g_id_signin noprint" title="Connect with Google" data-type="icon" data-shape="circle" data-theme="outline" data-text="signup_with" data-size="medium" data-locale="en"></span>
<?php endif; ?>
</p>
<?php if ($with_name): ?>
<p class="info">You may also enter your email address.</p>
<?php endif; ?>
<p class="inlabel<?php if ($missing_password or $access_denied): ?> inerror<?php endif; ?>">And your access key?</p>
<p><input type="password" name="login_password" id="login_password" size="20" maxlength="20" title="Password" onkeypress="<?php if ($with_captcha): ?>return focusonenter(event, 'login_code')<?php else: ?>return submitonenter(event, 'login_enter')<?php endif; ?>" /><?php if ($with_viewpassword): ?>&nbsp;<span class="icon icon_view pointer"></span><?php endif; ?></p>
<?php if ($password_page): ?>
<p class="info link">If you have forgotten your password, <a class="clickhere" href="<?php echo $password_page; ?>" rel="nofollow">click here</a>.</p>
<?php endif; ?>
<?php if ($with_captcha): ?>
<p>
<img src="<?php echo $base_path; ?>/captcha/login" alt="" height="40" title="Verification code" />
:
<input type="text" name="login_code" id="login_code" size="4" maxlength="4" title="4 letters" autocomplete="off" onkeypress="return submitonenter(event, 'login_enter')" value="" />
</p>
<?php endif; ?>
<p><input type="submit" class="submit submit_enter" name="login_enter" id="login_enter" value="Enter" /></p>
<?php if ($newuser_page): ?>
<p class="info link">To create your personal account, <a class="clickhere" href="<?php echo $newuser_page; ?>" rel="nofollow">click here</a>.</p>
<?php endif; ?>
</form>
<?php if ($with_viewpassword): ?>
<script>
(function() {
	const password = document.getElementById('login_password');
	password.nextElementSibling.addEventListener('click', () => password.type = password.type == 'password' ? 'text' : 'password');
})();
</script>
<?php endif; ?>
<div class="errors">
<?php if ($missing_code): ?>
<p>Enter the verification code displayed in the image.</p>
<?php elseif ($bad_code): ?>
<p>The verification code is incorrect.</p>
<?php endif; ?>
<?php if ($missing_login or $missing_password): ?>
<p>Enter your identifier and your password.</p>
<?php elseif ($bad_login): ?>
<p>The identifier is invalid.</p>
<?php elseif ($access_denied): ?>
<p>Access denied.</p>
<?php elseif ($not_confirmed): ?>
<p>You account is not validated.
A new link has been sent to your address.</p>
<?php endif; ?>
</div>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#login_code';
}
else if ($missing_login or $bad_login) {
	$focus='#login_login';
}
else if ($missing_password or $access_denied) {
	$focus='#login_password';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
