<?php

/**
 *
 * @copyright  2010-2019 izend.org
 * @version    28
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form method="post"<?php if ($with_attachment): ?> enctype="multipart/form-data"<?php endif; ?>>
<input type="hidden" name="mailme_token" value="<?php echo $token; ?>" />
<?php if ($with_attachment and $maxfilesize): ?>
<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $maxfilesize; ?>" />
<?php endif; ?>
<p class="inlabel<?php if ($missing_mail or $bad_mail): ?> inerror<?php endif; ?>">What is your email address?</p>
<p><input type="text" name="mailme_mail" id="mailme_mail" size="40" maxlength="100" title="Email" onkeypress="return focusonenter(event, 'mailme_subject')" value="<?php echo htmlspecialchars($mail, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<p class="info">Your email address is strictly confidential.</p>
<p class="inlabel<?php if ($missing_subject or $bad_subject or $missing_message): ?> inerror<?php endif; ?>">Type in the subject and the text of your message:</p>
<p><input type="text" name="mailme_subject" id="mailme_subject" size="40" maxlength="100" title="Subject" onkeypress="return focusonenter(event, 'mailme_message')" value="<?php echo htmlspecialchars($subject, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<textarea name="mailme_message" id="mailme_message" cols="50" rows="5" title="Text"><?php echo htmlspecialchars($message, ENT_COMPAT, 'UTF-8'); ?></textarea>
<?php if ($with_attachment): ?>
<p>
<input type="file" name="mailme_file" id="mailme_file" title="" />
<span class="hidden">
<input type="submit" class="submit submit_add" id="mailme_put" name="mailme_put" value="Add" />
an attachment
<span class="icon <?php if ($bad_attachment): ?>icon_ko<?php else: ?>icon_attachment<?php endif; ?>"><?php if ($bad_attachment): ?>-<?php else: ?>+<?php endif; ?></span>
</span>
</p>
<?php if ($maxfilesize): ?>
<?php require_once 'countformat.php'; ?>
<p class="info">You can upload a file up to <?php echo count_format($maxfilesize, '.', ''); ?> bytes.</p>
<?php endif; ?>
<?php endif; ?>
<?php if ($with_appointment): ?>
<p>
<span class="inlabel<?php if ($bad_appointment): ?> inerror<?php endif; ?>">Appointment on</span>
<input type="text" class="text_date" name="mailme_date" id="mailme_date" size="10" title="yyyy-mm-dd" onkeypress="return focusonenter(event, 'mailme_code')" value="<?php echo htmlspecialchars($date, ENT_COMPAT, 'UTF-8'); ?>" />
<span class="inlabel<?php if ($bad_appointment): ?> inerror<?php endif; ?>">at</span>
<select id="mailme_hour" name="mailme_hour" size="1">
<?php foreach (range(8, 18, 1) as $hh): ?>
<option value="<?php echo $hh; ?>"<?php if ($hour == $hh): ?> selected="selected"<?php endif; ?>><?php echo $hh > 9 ? $hh : '0' . $hh; ?></option>
<?php endforeach; ?>
</select>
<span class="inlabel<?php if ($bad_appointment): ?> inerror<?php endif; ?>">:</span>
<select id="mailme_minute" name="mailme_minute" size="1">
<?php foreach (range(0, 45, 15) as $mm): ?>
<option value="<?php echo $mm; ?>"<?php if ($minute == $mm): ?> selected="selected"<?php endif; ?>><?php echo $mm > 0 ? $mm : '0' . $mm; ?></option>
<?php endforeach; ?>
</select>
</p>
<?php endif; ?>
<?php if ($with_captcha): ?>
<p>
<img class="captcha" src="<?php echo $base_path; ?>/captcha/mailme" alt="" height="40" title="Verification code" />
:
<input type="text" name="mailme_code" id="mailme_code" size="4" maxlength="4" title="4 letters" autocomplete="off" onkeypress="return submitonenter(event, 'mailme_send')" value="" />
</p>
<?php endif; ?>
<p><input type="submit" class="submit submit_send" name="mailme_send" id="mailme_send" value="Send" /></p>
</form>
<div class="errors">
<?php if ($missing_code): ?>
<p>Enter the verification code displayed in the image.</p>
<?php elseif ($bad_code): ?>
<p>The verification code is incorrect.</p>
<?php endif; ?>
</div>
<?php extract($infos); ?>
<div class="infos">
<?php if ($internal_error): ?>
<p>An internal error has occurred.</p>
<?php endif; ?>
<?php if ($email_sent): ?>
<p>Your message has been sent to the webmaster.
<?php if ($home_page): ?>
To return to the home page, <a class="clickhere" href="<?php echo $home_page; ?>">click here</a>.
<?php endif; ?>
</p>
<?php endif; ?>
</div>
<?php if ($with_attachment): ?>
<script>
(function() {
	var file=$('#mailme_file');
	var upload=$('#mailme_put');

	upload.unwrap();

	file.css({ position: 'absolute', left: '-9999px' });

	upload.on('click', function(e) { e.preventDefault(); file.click(); });

	file.change(function() {
		if (file.val()) {
			upload.next().removeClass('icon_attachment').removeClass('icon_ko').addClass('icon_ok').text('+');
		}
	});
})();
</script>
<?php endif; ?>
<?php if ($with_appointment): ?>
<?php head('javascript', 'jquery-ui'); ?>
<?php head('stylesheet', 'jquery-ui', 'screen'); ?>
<script>
$('#mailme_date').datepicker({dateFormat: 'yy-mm-dd', autoSize: true, showAnim: 'drop', showOn: 'both', buttonText: 'Calendar', buttonImage: '/images/theme/edit/calendar.png', buttonImageOnly: true, minDate: '+1d', maxDate: '+2m', showOtherMonths: true, navigationAsDateFormat: true, prevText: 'MM', nextText: 'MM', beforeShowDay: function(date) {return [date.getDay() != 0];}});
</script>
<?php endif; ?>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#mailme_code';
}
else if ($missing_mail or $bad_mail) {
	$focus='#mailme_mail';
}
else if ($missing_subject or $bad_subject) {
	$focus='#mailme_subject';
}
else if ($missing_message) {
	$focus='#mailme_message';
}
else if ($bad_appointment) {
	$focus='#mailme_date';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
