<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php if ($comments or $newcomment or $user_page): ?>
<div id="comments">
<?php if (empty($comments)): ?>
<h4 class="noprint">Comments</h4>
<?php else: ?>
<h4>Comments</h4>
<?php endif; ?>
<?php echo $comments; ?>
<?php if ($newcomment): ?>
<?php echo $newcomment; ?>
<?php elseif ($user_page): ?>
<p class="info noprint">To add a comment, <a href="<?php echo $user_page; ?>" rel="nofollow">click here</a>.</p>
<?php endif; ?>
</div>
<?php endif; ?>
