<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<?php require_once 'dateen.php'; ?>
<h3><?php echo htmlspecialchars($node_title ? $node_title : $node_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<p class="info"><?php echo longdatetime_en($node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Abstract</h5>
<p><?php echo htmlspecialchars($node_abstract, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Cloud</h6>
<p class="small"><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_comment or $node_morecomment or $node_ilike or $node_tweet or $node_plusone): ?>
<fieldset id="node_options">
<legend>Options</legend>
<div class="hbar">
<?php if ($node_comment): ?><img src="<?php echo $base_path; ?>/images/theme/edit/comment.png" alt="" /><?php endif; ?>
<?php if ($node_morecomment): ?><img src="<?php echo $base_path; ?>/images/theme/edit/comment_add.png" alt="" /><?php endif; ?>
<?php if ($node_ilike): ?><img src="<?php echo $base_path; ?>/images/theme/edit/facebook.png" alt="" /><?php endif; ?>
<?php if ($node_tweet): ?><img src="<?php echo $base_path; ?>/images/theme/edit/twitter.png" alt="" /><?php endif; ?>
<?php if ($node_plusone): ?><img src="<?php echo $base_path; ?>/images/theme/edit/plusone.png" alt="" /><?php endif; ?>
</div>
</fieldset>
<?php endif; ?>
<?php if ($node_contents): ?>
<h4>Contents</h4>
<?php echo $node_contents; ?>
<?php endif; ?>
