<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<h3>Payment rejected</h3>
<p>Your payment of <?php number_format($amount, 2, '.', ','); ?>&nbsp;<?php echo $currency; ?> has been rejected. Thank you for trying again while checking your payment details.
<?php if (!empty($contact_page)): ?>If you think this is an error, please <a href="<?php echo $contact_page; ?>">contact us</a>.<?php endif; ?></p>
