<?php

/**
 *
 * @copyright  2013-2019 izend.org
 * @version    12
 * @link       http://www.izend.org
 */
?>
<?php switch ($mode): ?>
<?php case 'lite': ?>
<a href="https://pinterest.com/pin/create/button/?url=<?php echo urlencode($base_url . '/' . $request_path); ?><?php if (!empty($pinit_image)): ?>&amp;media=<?php echo urlencode($base_url . '/' . $pinit_image); ?><?php endif ?><?php if (!empty($pinit_text)): ?>&amp;description=<?php echo urlencode($pinit_text); ?><?php endif ?>" target="_blank" title="Share on Pinterest" data-pin-custom="true"><span>Pinterest</span></a>
<?php break; ?>
<?php case 'awesome': ?>
<a href="https://pinterest.com/pin/create/button/?url=<?php echo urlencode($base_url . '/' . $request_path); ?><?php if (!empty($pinit_image)): ?>&amp;media=<?php echo urlencode($base_url . '/' . $pinit_image); ?><?php endif ?><?php if (!empty($pinit_text)): ?>&amp;description=<?php echo urlencode($pinit_text); ?><?php endif ?>" target="_blank" title="Share on Pinterest" data-pin-custom="true"><i class="fab fa-pinterest-p"></i></a>
<?php break; ?>
<?php default: ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script>
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<a href="//www.pinterest.com/pin/create/button/?url=<?php echo urlencode($base_url . '/' . $request_path); ?><?php if (!empty($pinit_image)): ?>&media=<?php echo urlencode($base_url . '/' . $pinit_image); ?><?php endif ?><?php if (!empty($pinit_text)): ?>&description=<?php echo urlencode($pinit_text); ?><?php endif ?>" data-pin-save="false" data-pin-do="buttonPin"<?php if (false): ?> data-pin-count="above"<?php endif; ?> data-pin-color="white" data-pin-height="28"><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_white_28.png" /></a>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<a href="//www.pinterest.com/pin/create/button/?url=<?php echo urlencode($base_url . '/' . $request_path); ?><?php if (!empty($pinit_image)): ?>&media=<?php echo urlencode($base_url . '/' . $pinit_image); ?><?php endif ?><?php if (!empty($pinit_text)): ?>&description=<?php echo urlencode($pinit_text); ?><?php endif ?>" data-pin-save="false" data-pin-do="buttonPin"<?php if (false): ?> data-pin-count="beside"<?php endif; ?> data-pin-color="white"><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_white_20.png" /></a>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
<?php global $pinteresetassets; $pinteresetassets=true; ?>
<?php break; ?>
<?php endswitch; ?>
