<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<?php head('javascript', 'https://apis.google.com/js/plusone.js'); ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script type="text/javascript">
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<div class="g-plusone" data-href="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-size="tall" data-annotation="bubble"></div>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<div class="g-plusone" data-href="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-size="medium"></div>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
