<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<?php if ($search_input or $search_cloud): ?>
<div id="searchbox">
<?php if ($search_input): ?>
<form id="searchinput" action="<?php echo $search_url; ?>" method="post">
<input id="searchtext" name="searchtext" type="text" value="<?php echo htmlentities($search_text, ENT_COMPAT, 'UTF-8'); ?>" />
<button id="search" name="search" type="submit" title="Search">"Search"</button>
</form>
<?php endif; ?>
<?php if($search_cloud): ?>
<?php echo $search_cloud; ?>
<?php endif; ?>
</div>
<?php endif; ?>
