<?php

/**
 *
 * @copyright  2011 frasq.org
 * @version    1
 * @link       http://www.frasq.org
 */
?>
<p id="social">
<a href="http://www.facebook.com/" target="_blank"><img src="<?php echo $base_path; ?>/images/theme/social/facebook.png" alt="Facebook" /></a>
<a href="http://www.twitter.com/" target="_blank"><img src="<?php echo $base_path; ?>/images/theme/social/twitter.png" alt="Twitter" /></a>
<a href="<?php echo $base_path; ?>/en/rss" target="_blank"><img src="<?php echo $base_path; ?>/images/theme/social/rss.png" alt="RSS" /></a>
</p>
<script type="text/javascript">
$('#social img').hover(function() { $(this).animate({'opacity' : '0.5'}, 200); }, function() { $(this).animate({'opacity' : '1.0'}, 200); } );
</script>
