<?php

/**
 *
 * @copyright  2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<p id="social">
<a href="http://www.facebook.com/pages/frasqorg/235894459775696" target="_blank"><img src="<?php echo $base_path; ?>/images/theme/social/facebook.png" alt="Facebook" title="Connect with us on Facebook" /></a>
<a href="http://www.twitter.com/#!/frasqorg" target="_blank"><img src="<?php echo $base_path; ?>/images/theme/social/twitter.png" alt="Twitter" title="Follow us on Twitter" /></a>
<a href="<?php echo $base_path; ?>/en/rss" target="_blank"><img src="<?php echo $base_path; ?>/images/theme/social/rss.png" alt="RSS" title="Subscribe to the RSS feed" /></a>
</p>
<script type="text/javascript">
$('#social img').hover(function() { $(this).animate({'opacity' : '0.5'}, 200); }, function() { $(this).animate({'opacity' : '1.0'}, 200); } );
</script>
