<?php

/**
 *
 * @copyright  2012-2023 izend.org
 * @version    16
 * @link       http://www.izend.org
 */
?>
<span id="socialbar" class="menu noprint">
<a class="facebook" href="https://www.facebook.com/pages/" title="Join us on Facebook"><span>Facebook</span></a>
<?php if (false): ?>
<a class="twitter" href="https://twitter.com/#!/" title="Follow us on Twitter"><span>Twitter</span></a>
<?php endif; ?>
<a class="x_twitter" href="https://twitter.com/#!/" title="Follow us on X"><span>X</span></a>
<a class="linkedin" href="http://www.linkedin.com/" title="Connect to our network on LinkedIn"><span>LinkedIn</span></a>
<a class="youtube" href="https://www.youtube.com/channel/" title="Watch our videos on YouTube"><span>YouTube</span></a>
<a class="pinterest" href="https://www.pinterest.com/" title="Look at our pins on Pinterest"><span>Pinterest</span></a>
<a class="rss" href="<?php echo $base_path; ?>/en/rss" rel="nofollow" title="Subscribe to the RSS feed"><span>RSS</span></a>
<a class="newsletter" href="<?php echo $base_path; ?>/en/newsletter/subscribe" rel="nofollow" title="Receive our newsletter"><span>Newsletter</span></a>
<a class="email" href="<?php echo $base_path; ?>/en/contact" rel="nofollow" title="Contact us"><span>Email</span></a>
</span>
