<?php

/**
 *
 * @copyright  2010-2018 izend.org
 * @version    16
 * @link       http://www.izend.org
 */
?>
<?php require_once 'dateen.php'; ?>
<h3><?php echo $thread_title ? $thread_title : $thread_id; ?></h3>
<p class="compact">
<?php echo $inlanguages; ?>
<span id="thread_hidy" class="hidy">+</span>
</p>
<div id="thread">
<p class="info"><?php echo longdatetime_en($thread_modified); ?></p>
<?php if ($thread_abstract): ?>
<h5>Abstract</h5>
<p><?php echo $thread_abstract; ?></p>
<?php endif; ?>
<?php if ($thread_cloud): ?>
<h6>Cloud</h6>
<p class="small"><?php echo $thread_cloud; ?></p>
<?php endif; ?>
<?php if ($thread_image): ?>
<h6>Image</h6>
<p><img id="thread_image" src="<?php echo str_replace('%2F', '/', urlencode($thread_image)); ?>" alt="<?php echo htmlspecialchars($thread_image, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<?php endif; ?>
<?php if ($thread_search or $thread_tag or $thread_comment or $thread_morecomment or $thread_vote or $thread_morevote or $thread_ilike or $thread_tweet or $thread_plusone or $thread_linkedin or $thread_pinit): ?>
<fieldset id="thread_options">
<legend>Options</legend>
<div class="hbar">
<?php if ($thread_search): ?><span class="btn_edit btn_search">search</span><?php endif; ?>
<?php if ($thread_tag): ?><span class="btn_edit btn_tag">cloud</span><?php endif; ?>
<?php if ($thread_visits): ?><span class="btn_edit btn_visits">visits</span><?php endif; ?>
<?php if ($thread_comment): ?><span class="btn_edit btn_comment">comment</span><?php endif; ?>
<?php if ($thread_morecomment): ?><span class="btn_edit btn_morecomment">comment+</span><?php endif; ?>
<?php if ($thread_vote): ?><span class="btn_edit btn_vote">vote</span><?php endif; ?>
<?php if ($thread_morevote): ?><span class="btn_edit btn_morevote">vote+</span><?php endif; ?>
<?php if ($thread_ilike): ?><span class="btn_edit btn_ilike">facebook</span><?php endif; ?>
<?php if ($thread_tweet): ?><span class="btn_edit btn_tweet">twitter</span><?php endif; ?>
<?php if ($thread_plusone): ?><span class="btn_edit btn_plusone">google+</span><?php endif; ?>
<?php if ($thread_linkedin): ?><span class="btn_edit btn_linkedin">linkedin</span><?php endif; ?>
<?php if ($thread_pinit): ?><span class="btn_edit btn_pinit">pinit</span><?php endif; ?>
</div>
</fieldset>
<?php endif; ?>
</div>
<h4>Contents</h4>
<?php if ($thread_contents): ?>
<ol>
<?php foreach ($thread_contents as $c): ?>
<?php extract($c);	/* node_title node_url node_ignored */ ?>
<li><a href="<?php echo $node_url; ?>"><?php echo htmlspecialchars($node_title ? $node_title : $node_id, ENT_COMPAT, 'UTF-8'); ?></a><?php if ($node_ignored): ?> <span class="btn_edit btn_ignored">X</span><?php endif; ?></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
<?php head('javascript', 'jquery.cookie'); ?>
<script>
if ($.cookie('hidethread') == 1) {
	$('#thread').hide();
}
$('#thread_hidy').click(function() {
	$('#thread').toggle();
	$.cookie('hidethread', $('#thread').is(':hidden') ? 1 : 0, { path: '/' });
});
</script>
