<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<?php require_once 'dateen.php'; ?>
<h3><?php echo $node_title; ?></h3>
<p id="threadnodenav" class="menubar">
<?php if ($prev_node_url): ?>
<a href="<?php echo $prev_node_url; ?>"><img src="/images/theme/icons/left.png" alt=""/></a>
<a href="<?php echo $prev_node_url; ?>"><?php echo htmlspecialchars($prev_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<?php endif; ?>
<?php if ($next_node_url and $prev_node_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_node_url): ?>
<a href="<?php echo $next_node_url; ?>"><?php echo htmlspecialchars($next_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<a href="<?php echo $next_node_url; ?>"><img src="/images/theme/icons/right.png" alt=""/></a>
<?php endif; ?>
</p>
<p class="info"><?php echo longdatetime_en($node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Abstract</h5>
<p><?php echo $node_abstract; ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Cloud</h6>
<p class="smaller"><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_contents): ?>
<h4>Content</h4>
<?php echo $node_contents; ?>
<?php endif; ?>
