<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    9
 * @link       http://www.izend.org
 */
?>
<?php require_once 'dateen.php'; ?>
<div id="threadnode">
<h3><?php echo htmlspecialchars($node_title ? $node_title : $node_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<p class="navigation menu">
<?php if ($prev_node_url): ?>
<a class="previous" href="<?php echo $prev_node_url; ?>"><span>&lt;</span></a>
<a href="<?php echo $prev_node_url; ?>"><?php echo htmlspecialchars($prev_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<?php endif; ?>
<?php if ($next_node_url and $prev_node_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_node_url): ?>
<a href="<?php echo $next_node_url; ?>"><?php echo htmlspecialchars($next_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<a class="next" href="<?php echo $next_node_url; ?>"><span>&gt;</span></a>
<?php endif; ?>
</p>
<p class="info"><?php echo longdatetime_en($node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Abstract</h5>
<p><?php echo $node_abstract; ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Cloud</h6>
<p class="small"><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_comment or $node_morecomment or $node_vote or $node_morevote or $node_ilike or $node_tweet or $node_plusone): ?>
<fieldset id="node_options">
<legend>Options</legend>
<div class="hbar">
<?php if ($node_comment): ?><span class="btn_edit btn_comment">comment</span><?php endif; ?>
<?php if ($node_morecomment): ?><span class="btn_edit btn_morecomment">comment+</span><?php endif; ?>
<?php if ($node_vote): ?><span class="btn_edit btn_vote">vote</span><?php endif; ?>
<?php if ($node_morevote): ?><span class="btn_edit btn_morevote">vote+</span><?php endif; ?>
<?php if ($node_ilike): ?><span class="btn_edit btn_ilike">facebook</span><?php endif; ?>
<?php if ($node_tweet): ?><span class="btn_edit btn_tweet">twitter</span><?php endif; ?>
<?php if ($node_plusone): ?><span class="btn_edit btn_plusone">google+</span><?php endif; ?>
<?php if ($node_linkedin): ?><span class="btn_edit btn_linkedin">linkedin</span><?php endif; ?>
</div>
</fieldset>
<?php endif; ?>
<?php if ($node_contents): ?>
<h4>Content</h4>
<div id="threadnodecontent">
<?php echo $node_contents; ?>
</div>
<?php endif; ?>
</div>
