<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3><?php echo $node_title; ?></h3>
<p id="threadnodenav" class="menubar">
<?php if ($prev_node_url): ?>
<a href="<?php echo $prev_node_url; ?>" title="Previous"><?php echo $prev_node_label; ?></a>
<?php endif; ?>
<?php if ($next_node_url and $prev_node_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_node_url): ?>
<a href="<?php echo $next_node_url; ?>" title="Next"><?php echo $next_node_label; ?></a>
<?php endif; ?>
</p>
<p class="info"><?php setlocale(LC_TIME, 'en_US.UTF-8'); echo strftime('%B %e, %Y %Hh%M', $node_modified); ?></p>
<?php if ($node_abstract): ?>
<h5>Abstract</h5>
<p><?php echo $node_abstract; ?></p>
<?php endif; ?>
<?php if ($node_cloud): ?>
<h6>Cloud</h6>
<p class="smaller"><?php echo htmlentities($node_cloud, ENT_COMPAT, 'UTF-8'); ?></p>
<?php endif; ?>
<?php if ($node_contents): ?>
<h4>Content</h4>
<?php echo $node_contents; ?>
<?php endif; ?>
