<?php

/**
 *
 * @copyright  2015 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<p id="twitter-timeline"><a class="twitter-timeline" href="https://twitter.com/<?php echo $link_tweetline; ?>" lang="en" width="360" data-link-color="#eb4823"<?php if (!empty($tweetline_limit)): ?> data-tweet-limit="<?php echo $tweetline_limit; ?>"<?php endif; ?> data-chrome="noborders nofooter noscrollbar transparent" data-widget-id="<?php echo $tweetline_widget_id; ?>">Tweets about @<?php echo $link_tweetline;?></a></p>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
