<?php

/**
 *
 * @copyright  2010-2015 izend.org
 * @version    8
 * @link       http://www.izend.org
 */
?>
<?php if ($mode == 'lite'): ?>
<a class="twitter" href="https://twitter.com/home?status=<?php if (!empty($tweet_text)): ?><?php echo htmlentities($tweet_text, ENT_QUOTES, 'UTF-8'); ?> - <?php endif; ?><?php echo urlencode($base_url . '/' . $request_path); ?>" target="_blank" title="Share on Twitter"><span>Twitter</span></a>
<?php else: ?>
<?php head('javascript', 'https://platform.twitter.com/widgets.js'); ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script type="text/javascript">
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<a href="https://twitter.com/share" class="twitter-share-button"<?php if (!empty($tweet_text)): ?> data-text="<?php echo htmlentities($tweet_text, ENT_QUOTES, 'UTF-8'); ?>"<?php endif; ?> data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-count="vertical" data-lang="en"></a>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<a href="https://twitter.com/share" class="twitter-share-button"<?php if (!empty($tweet_text)): ?> data-text="<?php echo htmlentities($tweet_text, ENT_QUOTES, 'UTF-8'); ?>"<?php endif; ?> data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-count="horizontal" data-lang="en"></a>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
<?php endif; ?>
