<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<?php head('javascript', 'http://platform.twitter.com/widgets.js'); ?>
<?php $id = uniqid('id'); ?>
<div id="<?php echo $id; ?>"></div>
<script type="text/javascript">
//<![CDATA[
<?php switch ($mode): ?>
<?php case 'bar': ?>
$('#<?php echo $id; ?>').replaceWith('<a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-count="vertical" data-lang="en"></a>');
<?php break; ?>
<?php case 'inline': ?>
<?php default: ?>
$('#<?php echo $id; ?>').replaceWith('<a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php echo $base_url; ?>/<?php echo $request_path; ?>" data-count="horizontal" data-lang="en"></a>');
<?php break; ?>
<?php endswitch; ?>
//]]>
</script>
