<?php

/**
 *
 * @copyright  2011 izend.org
 * @version    8
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form action="" method="post">
<input type="hidden" name="useredit_token" value="<?php echo $token; ?>" />
<?php if ($user_accessed): ?>
<input type="hidden" name="useredit_accessed" value="<?php echo $user_accessed; ?>" />
<?php endif; ?>
<?php if ($with_name): ?>
<p class="inlabel<?php if ($missing_name or $bad_name or $duplicated_name): ?> inerror<?php endif; ?>">Connection name:</p>
<p><input id="useredit_name" type="text" name="useredit_name" size="20" maxlength="20" title="2 to 20 letters" onkeypress="return submitonenter(event, 'useredit_modify')" value="<?php echo htmlspecialchars($user_name, ENT_COMPAT, 'UTF-8'); ?>" /><?php if (!empty($user_name)): ?>&nbsp;<img class="avatar" src="<?php echo $base_path; ?>/avatars/<?php echo $user_name; ?>.png" /><?php endif; ?></p>
<?php else: ?>
<input type="hidden" name="useredit_name" value="<?php echo htmlspecialchars($user_name, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<p class="inlabel<?php if ($missing_mail or $bad_mail or $duplicated_mail): ?> inerror<?php endif; ?>">Email address:</p>
<p><input id="useredit_mail" type="text" name="useredit_mail" size="40" maxlength="100" title="name@domain.net" onkeypress="return submitonenter(event, 'useredit_modify')" value="<?php echo htmlspecialchars($user_mail, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<?php if ($with_website): ?>
<p class="inlabel<?php if ($bad_website): ?> inerror<?php endif; ?>">Website:</p>
<p><input id="useredit_website" type="text" name="useredit_website" size="40" maxlength="100" title="www.domain.com" onkeypress="return submitonenter(event, 'useredit_modify')" value="<?php echo htmlspecialchars($user_website, ENT_COMPAT, 'UTF-8'); ?>" /></p>
<?php else: ?>
<input type="hidden" name="useredit_website" value="<?php echo htmlspecialchars($useredit_website, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<?php if ($with_locale): ?>
<p><?php foreach ($system_languages as $lang): ?> <input name="useredit_locale" type="radio" value="<?php echo $lang; ?>" <?php if ($lang == $user_locale) echo 'checked="checked"'; ?> /> <?php echo $lang; ?><?php endforeach; ?></p>
<?php else: ?>
<input type="hidden" name="useredit_locale" value="<?php echo htmlspecialchars($user_locale, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<?php if ($with_status): ?>
<fieldset id="useredit_status">
<legend>Status</legend>
<input name="useredit_active" type="checkbox" <?php if ($user_active) echo 'checked="checked"'; ?> />&nbsp;active
<input name="useredit_banned" type="checkbox" <?php if ($user_banned) echo 'checked="checked"'; ?> />&nbsp;banned
</fieldset>
<?php if ($user_accessed): ?>
<?php require_once 'dateen.php'; ?>
<p><span id="useredit_accessed">Last access <?php echo longdate_en($user_accessed); ?> at <?php echo date('H:i', $user_accessed); ?></span></p>
<?php endif; ?>
<?php endif; ?>
<p>
<?php if ($with_delete): ?>
<?php if ($confirm_delete): ?>
<input type="submit" class="submit_confirm" name="useredit_confirmdelete" id="useredit_confirmdelete" value="Confirm" />
delete or
<input type="submit" class="submit_cancel" name="useredit_cancel" id="useredit_cancel" value="Cancel" />
<?php else: ?>
<input type="submit" class="submit_modify" name="useredit_modify" id="useredit_modify" value="Modify" />
the profile or
<input type="submit" class="submit_delete" name="useredit_delete" id="useredit_delete" value="Delete" />
the account
<?php endif; ?>
<?php else: ?>
<input type="submit" class="submit_modify" name="useredit_modify" id="useredit_modify" value="Modify" />
<?php endif; ?>
<?php if ($with_newpassword): ?>
<p class="inlabel<?php if ($missing_newpassword or $bad_newpassword): ?> inerror<?php endif; ?>">Password:</p>
<p><input type="password" name="useredit_newpassword" id="useredit_newpassword" size="20" maxlength="20" title="> 6 letters and digits" onkeypress="return submitonenter(event, 'useredit_change')" value="<?php echo $user_newpassword; ?>" /></p>
<input type="submit" class="submit_change" name="useredit_change" id="useredit_change" value="Change" />
<?php endif; ?>
</p>
</form>
<?php if ($missing_name): ?>
<p class="error">An identifier is required.</p>
<?php elseif ($bad_name): ?>
<p class="error">An identifier must contain between 2 and 20 letters.</p>
<?php elseif ($duplicated_name): ?>
<p class="error">This identifier is already taken.</p>
<?php endif; ?>
<?php if ($missing_mail): ?>
<p class="error">An email address is required.</p>
<?php elseif ($bad_mail): ?>
<p class="error">The email address is invalid.</p>
<?php elseif ($duplicated_mail): ?>
<p class="error">This email address is already being used.</p>
<?php endif; ?>
<?php if ($bad_website): ?>
<p class="error">The URL of the website is invalid.</p>
<?php endif; ?>
<?php if ($missing_newpassword or $bad_newpassword): ?>
<p class="error">Enter a combination of letters and digits of at least 6 characters.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p class="error">An internal error has occurred.
<?php if ($contact_page): ?>If you can describe the problem, please <a href="<?php echo $contact_page; ?>" rel="nofollow">contact us</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($infos): extract($infos); ?>
<?php if ($account_modified): ?>
<p>The account information has been modified.</p>
<?php endif; ?>
<?php if ($password_changed): ?>
<p>The password was changed.</p>
<?php endif; ?>
<?php endif; ?>
<?php
$focus=false;
if ($missing_name or $bad_name or $duplicated_name) {
	$focus='#useredit_name';
}
else if ($missing_mail or $bad_mail or $duplicated_mail) {
	$focus='#useredit_mail';
}
else if ($bad_website) {
	$focus='#useredit_website';
}
else if ($missing_newpassword or $bad_newpassword) {
	$focus='#useredit_newpassword';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
