<?php

/**
 *
 * @copyright  2014-2018 izend.org
 * @version    5
 * @link       http://www.izend.org
 */
?>
<?php if ($visits > 0): ?>
<?php require_once 'countformat.php'; ?>
<div class="visits" title="<?php echo number_format($visits, 0, '.', ','); ?> visit<?php if ($visits > 1): ?>s<?php endif; ?>"><?php echo count_format($visits, '.', ','); ?></div>
<?php endif; ?>
<?php if ($visit_page): ?>
<script>
$(document).ready(function() {$.get('<?php echo $visit_page; ?>');});
</script>
<?php endif; ?>
