<?php

/**
 *
 * @copyright  2019 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<?php switch ($mode): ?>
<?php case 'lite': ?>
<a href="whatsapp://send?text=<?php echo rawurlencode("$base_url/$request_path"); ?>" title="Share on WhatsApp"><span>WhatsApp</span></a>
<?php break; ?>
<?php case 'awesome': ?>
<a href="whatsapp://send?text=<?php echo rawurlencode("$base_url/$request_path"); ?>" title="Share on WhatsApp"><i class="fab fa-whatsapp"></i></a>
<?php break; ?>
<?php default: ?>
<?php break; ?>
<?php endswitch; ?>
