<?php

/**
 *
 * @copyright  2010-2020 izend.org
 * @version    8
 * @link       http://www.izend.org
 */
?>
<!DOCTYPE html>
<html<?php if (!empty($clang)): ?> lang="<?php echo $clang; ?>"<?php endif; ?>>
<head>
<?php echo $head; ?>
</head>
<body>
<?php if (!empty($trace)): ?>
<div>
<?php foreach ($trace as $s): ?>
<?php echo $s; ?>
<?php endforeach; ?>
</div>
<?php endif; ?>
<div id="editor">
<?php echo $banner; ?>
<div id="content">
<?php if (!empty($toolbar)): ?>
<?php echo $toolbar; ?>
<?php endif; ?>
<?php if (!empty($sidebar)): ?>
<?php echo $sidebar; ?>
<?php endif; ?>
<div id="body">
<?php echo $content; ?>
</div>
</div>
</div>
</body>
</html>
