<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    5
 * @link       http://www.izend.org
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $head; ?>
</head>
<body>
<div id="editor">
<?php echo $banner; ?>
<div id="bannerline"></div>
<div id="content">
<?php if (!empty($toolbar)): ?>
<?php echo $toolbar; ?>
<?php endif; ?>
<?php if (!empty($sidebar)): ?>
<?php echo $sidebar; ?>
<?php endif; ?>
<div id="body">
<?php echo $content; ?>
</div>
</div>
</div>
</body>
</html>
