<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:twitter="http://api.twitter.com/">
<head>
<?php echo $head; ?>
</head>
<body>
<div id="viewer">
<?php echo $banner; ?>
<div id="bannerline"></div>
<?php if (isset($sidebar) and !empty($sidebar)): ?>
<div id="sidebar">
<?php echo $sidebar; ?>
</div>
<?php endif; ?>
<div id="content">
<?php echo $content; ?>
</div>
<?php if (isset($footer) and !empty($footer)): ?>
<?php echo $footer; ?>
<?php endif; ?>
</div>
</body>
</html>
