<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    8
 * @link       http://www.izend.org
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<?php echo $head; ?>
</head>
<body>
<div id="standard">
<?php echo $banner; ?>
<div id="bannerline"></div>
<div id="content">
<?php if (!empty($sharebar)): ?>
<?php echo $sharebar; ?>
<?php endif; ?>
<?php if (!empty($toolbar)): ?>
<?php echo $toolbar; ?>
<?php endif; ?>
<?php if (!empty($sidebar)): ?>
<?php echo $sidebar; ?>
<?php endif; ?>
<div id="body">
<?php echo $content; ?>
</div>
</div>
<?php if (!empty($footer)): ?>
<?php echo $footer; ?>
<?php endif; ?>
</div>
</body>
</html>
