<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3>URL non trouvée</h3>
<p>L'URL demandée n'a pas été trouvée sur ce serveur.
Si vous avez tapé l'URL à la main, veuillez vérifier la saisie et réessayer.
<?php if ($contact_page): ?>Si vous pensez qu'il s'agit d'une erreur du serveur, merci de <a href="<?php echo $contact_page; ?>">nous contacter</a>.<?php endif; ?></p>
