<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php foreach ($supported_languages as $lng): ?>
<input name="<?php echo $lng; ?>" id="<?php echo $lng; ?>" type="submit" value="<?php echo $lng; ?>"/>
<?php endforeach; ?>
</p>
<p>
<input id="node_title" name="node_title" type="text" size="40" maxlength="100" value="<?php echo htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8'); ?>" title="Title" onkeypress="return submitonenter(event, 'node_edit')"/>
<label>URL:</label>
<input id="node_name" name="node_name" type="text" size="40" maxlength="100" value="<?php echo $node_name; ?>" onkeypress="return focusonenter(event, 'node_title')"/>
</p>
<p><label>Abstract:</label></p>
<p>
<textarea name="node_abstract" cols="80" rows="3"><?php echo htmlspecialchars($node_abstract, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" />
</p>
<p><label>Cloud:</label></p>
<p>
<textarea name="node_cloud" cols="80" rows="2" ><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" />
</p>
<p>
<input name="node_comment" name="node_comment" type="checkbox" <?php if ($node_comment) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/comment.png" alt="" />
<input name="node_morecomment" type="checkbox" <?php if ($node_morecomment) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/comment_add.png" alt="" />
</p>
<p>
<input id="node_edit" name="node_edit" type="submit" value="Edit" />
</p>
<?php if ($missing_node_title or $missing_node_name or $bad_node_name): ?>
<div class="alert">
<?php if ($missing_node_title): ?>
<p>You didn't input the title.</p>
<?php endif; ?>
<?php if ($missing_node_name): ?>
<p>Specify a name for the link.</p>
<?php elseif ($bad_node_name): ?>
<p>The name of the link is invalid.</p>
<?php endif; ?>
</div>
<?php endif; ?>
</form>
<h4>Contents</h4>
<?php echo $content_editor; ?>
