<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    10
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php echo $inlanguages; ?>
</p>
<p>
<input id="node_title" name="node_title" type="text" size="40" maxlength="100" value="<?php echo htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8'); ?>" title="Title" onkeypress="return submitonenter(event, 'node_edit')"/>
<label>URL:</label>
<input id="node_name" name="node_name" type="text" size="40" maxlength="100" value="<?php echo $node_name; ?>" onkeypress="return focusonenter(event, 'node_title')"/>
</p>
<p><label>Abstract:</label></p>
<p>
<textarea name="node_abstract" cols="80" rows="3"><?php echo htmlspecialchars($node_abstract, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" />
</p>
<p><label>Cloud:</label></p>
<p>
<textarea name="node_cloud" cols="80" rows="2" ><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" />
</p>
<fieldset id="node_options">
<legend>Options</legend>
<input name="node_comment" type="checkbox"<?php if ($node_comment): ?> checked="checked"<?php endif; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/comment.png" alt="" />
<input name="node_morecomment" type="checkbox"<?php if ($node_morecomment): ?> checked="checked"<?php endif; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/comment_add.png" alt="" />
<input name="node_ilike" type="checkbox"<?php if ($node_ilike): ?> checked="checked"<?php endif; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/facebook.png" alt="" />
<input name="node_tweet" type="checkbox"<?php if ($node_tweet): ?> checked="checked"<?php endif; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/twitter.png" alt="" />
<input name="node_plusone" type="checkbox"<?php if ($node_plusone): ?> checked="checked"<?php endif; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/plusone.png" alt="" />
<input name="node_linkedin" type="checkbox"<?php if ($node_linkedin): ?> checked="checked"<?php endif; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/linkedin.png" alt="" />
</fieldset>
<p>
<input class="submit_edit" id="node_edit" name="node_edit" type="submit" value="Edit" />
</p>
</form>
<?php
$focus=false;
if ($missing_node_name or $bad_node_name) {
	 $focus='#node_name';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
<h4>Contents</h4>
<?php echo $content_editor; ?>
