<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    12
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php echo $inlanguages; ?>
</p>
<p>
<input id="node_title" name="node_title" type="text" size="40" maxlength="100" value="<?php echo htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8'); ?>" title="Title" onkeypress="return submitonenter(event, 'node_edit')"/>
<label>URL:</label>
<input id="node_name" name="node_name" type="text" size="40" maxlength="100" value="<?php echo $node_name; ?>" onkeypress="return focusonenter(event, 'node_title')"/>
</p>
<p><label>Abstract:</label></p>
<p>
<textarea name="node_abstract" cols="80" rows="3"><?php echo htmlspecialchars($node_abstract, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><span class="grippie btn_edit btn_grippie">===</span>
</p>
<p><label>Cloud:</label></p>
<p>
<textarea name="node_cloud" cols="80" rows="2" ><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><span class="grippie btn_edit btn_grippie">===</span>
</p>
<fieldset id="node_options">
<legend>Options</legend>
<input id="node_comment" name="node_comment" type="checkbox"<?php if ($node_comment): ?> checked="checked"<?php endif; ?> /><label for="node_comment"><span class="btn_edit btn_comment">comment</span></label>
<input id="node_morecomment" name="node_morecomment" type="checkbox"<?php if ($node_morecomment): ?> checked="checked"<?php endif; ?> /><label for="node_morecomment"><span class="btn_edit btn_morecomment">comment+</span></label>
<input id="node_vote" name="node_vote" type="checkbox"<?php if ($node_vote): ?> checked="checked"<?php endif; ?> /><label for="node_vote"><span class="btn_edit btn_vote">vote</span></label>
<input id="node_morevote" name="node_morevote" type="checkbox"<?php if ($node_morevote): ?> checked="checked"<?php endif; ?> /><label for="node_morevote"><span class="btn_edit btn_morevote">vote+</span></label>
<input id="node_ilike" name="node_ilike" type="checkbox"<?php if ($node_ilike): ?> checked="checked"<?php endif; ?> /><label for="node_ilike"><span class="btn_edit btn_ilike">facebook</span></label>
<input id="node_tweet" name="node_tweet" type="checkbox"<?php if ($node_tweet): ?> checked="checked"<?php endif; ?> /><label for="node_tweet"><span class="btn_edit btn_tweet">twitter</span></label>
<input id="node_plusone" name="node_plusone" type="checkbox"<?php if ($node_plusone): ?> checked="checked"<?php endif; ?> /><label for="node_plusone"><span class="btn_edit btn_plusone">google+</span></label>
<input id="node_linkedin" name="node_linkedin" type="checkbox"<?php if ($node_linkedin): ?> checked="checked"<?php endif; ?> /><label for="node_linkedin"><span class="btn_edit btn_linkedin">linkedin</span></label>
</fieldset>
<p>
<input class="submit submit_edit" id="node_edit" name="node_edit" type="submit" value="Edit" />
</p>
</form>
<?php
$focus=false;
if ($missing_node_name or $bad_node_name) {
	 $focus='#node_name';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
<h4>Contents</h4>
<?php echo $content_editor; ?>
