<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php $scroll_to=false; ?>
<h3>Threads</h3>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php foreach ($supported_languages as $lng): ?>
<?php if ($lng == 'fr'): ?>
<input name="<?php echo $lng; ?>" id="<?php echo $lng; ?>" type="submit" value="Français" class="<?php if ($lng == $clang): ?>selected<?php endif; ?>"/>
<?php elseif ($lng == 'en'): ?>
<input name="<?php echo $lng; ?>" id="<?php echo $lng; ?>" type="submit" value="English" class="<?php if ($lng == $clang): ?>selected<?php endif; ?>"/>
<?php elseif ($lng == 'ar'): ?>
<input name="<?php echo $lng; ?>" id="<?php echo $lng; ?>" type="submit" value="عربي" class="<?php if ($lng == $clang): ?>selected<?php endif; ?>"/>
<?php endif; ?>
<?php endforeach; ?>
</p>
<p>
<input id="thread_create" name="thread_create" type="submit" value="Add" />
thread
<input id="new_thread_title" name="new_thread_title" type="text" size="50" maxlength="100" value="<?php echo htmlspecialchars($new_thread_title, ENT_COMPAT, 'UTF-8'); ?>" title="Title" title="Titre" onkeypress="return focusonenter(event, 'new_thread_number')"/>
#
<input id="new_thread_number" name="new_thread_number" type="text" size="2" maxlength="<?php echo $maxlen; ?>" value="<?php echo htmlspecialchars($new_thread_number, ENT_COMPAT, 'UTF-8'); ?>" title="Number" onkeypress="return submitonenter(event, 'thread_create')"/>
type
<?php
$selected=$new_thread_type ? $new_thread_type : 'thread';
?>
<select name="new_thread_type" size="1">
<option value="thread" <?php echo $selected == 'thread' ? 'selected="selected"' : ''; ?>>Thread</option>
<?php foreach ($supported_threads as $thd): ?>
<?php if ($thd == 'folder'): ?>
<option value="folder" <?php echo $selected == 'folder' ? 'selected="selected"' : ''; ?>>Folder</option>
<?php elseif ($thd == 'story'): ?>
<option value="story" <?php echo $selected == 'story' ? 'selected="selected"' : ''; ?>>Article</option>
<?php elseif ($thd == 'book'): ?>
<option value="book" <?php echo $selected == 'book' ? 'selected="selected"' : ''; ?>>Manual</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
</p>
<?php if ($missing_new_thread_title or $missing_new_thread_name or $missing_new_thread_type or $bad_new_thread_type or $bad_new_thread_number): ?>
<div class="alert">
<?php if ($missing_new_thread_title): ?>
<p>You didn't input the title of the new thread.</p>
<?php endif; ?>
<?php if ($missing_new_thread_name): ?>
<p>Specify a name for the link to the new thread.</p>
<?php elseif ($bad_new_thread_name): ?>
<p>The name of the link to the new thread is invalid.</p>
<?php endif; ?>
<?php if ($missing_new_thread_type): ?>
<p>Specify the type of the thread.</p>
<?php elseif ($bad_new_thread_type): ?>
<p>The type of the thread is invalid.</p>
<?php endif; ?>
<?php if ($bad_new_thread_number): ?>
<p>The new thread number is not correct.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($thread_list): ?>
<fieldset>
<legend>Catalog</legend>
<table cellpadding="2" cellspacing="0">
<tbody>
<?php
$i=1;
$maxlen=strlen(count($thread_list))+1;
foreach ($thread_list as $b) {
	extract($b);	/* pos, thread_id, thread_title, thread_number, thread_url */
	$thread_title = htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8');
	$thread_url .= '?' . 'clang=' . $clang;
	echo <<<_MARK_
<tr><td><input name="p[$i]" type="text" size="2" maxlength="$maxlen" value="$pos" /></td><td class="aright"><a href="$thread_url">$thread_number</a></td><td><a href="$thread_url">$thread_title</a></td></tr>\n
_MARK_;
	$i++;
}
?>
</tbody>
</table>
</fieldset>
<p>
<input id="threadlist_reorder" name="threadlist_reorder" type="submit" value="Reorder" />
the list or
<input id="thread_delete" name="thread_delete" type="submit" value="Delete" />
the thread #
<input id="old_thread_number" name="old_thread_number" type="text" size="2" maxlength="<?php echo $maxlen; ?>" value="<?php echo htmlspecialchars($old_thread_number, ENT_COMPAT, 'UTF-8'); ?>" title="Number" onkeypress="return submitonenter(event, 'thread_delete')"/>
<?php if ($confirm_delete_thread): ?>
Really?&nbsp;<button id="thread_confirmdelete" name="thread_confirmdelete" type="submit">Confirm</button>
<?php endif; ?>
</p>
<?php if ($missing_old_thread_number or $bad_old_thread_number): ?>
<?php $scroll_to='#thread_delete'; ?>
<div class="alert">
<?php if ($missing_old_thread_number): ?>
<p>You didn't specify the thread number to delete.</p>
<?php elseif ($bad_old_thread_number): ?>
<p>The thread number to delete is not correct.</p>
<?php endif; ?>
</div>
<?php endif; ?>
<?php endif; ?>
</form>
<?php if ($scroll_to): ?>
<script type="text/javascript">
$(document).ready(function() {
	$(window).scrollTo('<?php echo $scroll_to; ?>');
});
</script>
<?php endif; ?>
