<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    1
 * @link       http://www.izend.org
 */
?>
<h3><?php echo htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8'); ?></h3>
<?php if ($next_node_url or $prev_node_url): ?>
<p id="threadnodenav" class="menubar">
<?php if ($prev_node_url): ?>
<a href="<?php echo $prev_node_url; ?>"><img src="/images/theme/icons/left.png" alt=""/></a>
<a href="<?php echo $prev_node_url; ?>"><?php echo htmlspecialchars($prev_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<?php endif; ?>
<?php if ($next_node_url and $prev_node_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_node_url): ?>
<a href="<?php echo $next_node_url; ?>"><?php echo htmlspecialchars($next_node_label, ENT_COMPAT, 'UTF-8'); ?></a>
<a href="<?php echo $next_node_url; ?>"><img src="/images/theme/icons/right.png" alt=""/></a>
<?php endif; ?>
</p>
<?php endif; ?>
<?php echo $node_editor; ?>
