<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    8
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php $scroll_to=false; ?>
<h3><?php echo htmlspecialchars($thread_title ? $thread_title : $thread_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<form class="compact" action="" method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<p>
<?php foreach ($supported_languages as $lng): ?>
<?php if ($lng == 'fr'): ?>
<input name="<?php echo $lng; ?>" id="<?php echo $lng; ?>" type="submit" value="Français" class="<?php if ($lng == $clang): ?>selected<?php endif; ?>"/>
<?php elseif ($lng == 'en'): ?>
<input name="<?php echo $lng; ?>" id="<?php echo $lng; ?>" type="submit" value="English" class="<?php if ($lng == $clang): ?>selected<?php endif; ?>"/>
<?php elseif ($lng == 'ar'): ?>
<input name="<?php echo $lng; ?>" id="<?php echo $lng; ?>" type="submit" value="عربي" class="<?php if ($lng == $clang): ?>selected<?php endif; ?>"/>
<?php endif; ?>
<?php endforeach; ?>
</p>
<p>
<input id="thread_title" name="thread_title" type="text" size="40" maxlength="100" value="<?php echo htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8'); ?>" title="Title" onkeypress="return submitonenter(event, 'thread_edit')"/>
<label>URL:</label>
<input id="thread_name" name="thread_name" type="text" size="40" maxlength="100" value="<?php echo $thread_name; ?>" onkeypress="return submitonenter(event, 'thread_edit')"/>
</p>
<p><label>Abstract:</label></p>
<p>
<textarea name="thread_abstract" cols="80" rows="5"><?php echo htmlspecialchars($thread_abstract, ENT_COMPAT, 'UTF-8'); ?></textarea>
<br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" alt="===" />
</p>
<p><label>Cloud:</label></p>
<p>
<textarea name="thread_cloud" cols="80" rows="5"><?php echo htmlspecialchars($thread_cloud, ENT_COMPAT, 'UTF-8'); ?></textarea><br/><img class="grippie" src="<?php echo $base_path; ?>/images/theme/edit/grippie.png" />
</p>
<p>
<label>Type:</label>
<select name="thread_type" size="1">
<option value="thread" <?php echo $thread_type == 'thread' ? 'selected="selected"' : ''; ?>>Thread</option>
<?php foreach ($supported_threads as $thd): ?>
<?php if ($thd == 'folder'): ?>
<option value="folder" <?php echo $thread_type == 'folder' ? 'selected="selected"' : ''; ?>>Folder</option>
<?php elseif ($thd == 'story'): ?>
<option value="story" <?php echo $thread_type == 'story' ? 'selected="selected"' : ''; ?>>Article</option>
<?php elseif ($thd == 'book'): ?>
<option value="book" <?php echo $thread_type == 'book' ? 'selected="selected"' : ''; ?>>Manual</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
</p>
<p>
<input name="thread_search" type="checkbox" <?php if ($thread_search) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/search.png" alt="" />
<input name="thread_tag" type="checkbox" <?php if ($thread_tag) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/tag.png" alt="" />
<input name="thread_comment" type="checkbox" <?php if ($thread_comment) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/comment.png" alt="" />
<input name="thread_morecomment" type="checkbox" <?php if ($thread_morecomment) echo 'checked="checked"'; ?> /><img src="<?php echo $base_path; ?>/images/theme/edit/comment_add.png" alt="" />
</p>
<p>
<input id="thread_edit" name="thread_edit" type="submit" value="Edit" />
</p>
<script type="text/javascript">
$(document).ready(function() {
	$('.grippie').each(function() {
		var grippie = $(this);
		var textarea = grippie.prev().prev();
		var offset;

		grippie.mousedown(startDrag);

	    function startDrag(e) {
	      offset = textarea.height() - e.pageY;
	      textarea.css('opacity', 0.25);
	      $(document).mousemove(performDrag).mouseup(endDrag);
	      return false;
	    }

	    function performDrag(e) {
	      textarea.height(Math.max(32, offset + e.pageY) + 'px');
	      return false;
	    }

	    function endDrag(e) {
	      $(document).unbind('mousemove', performDrag).unbind('mouseup', endDrag);
	      textarea.css('opacity', 1);
	    }
	});
});
</script>
<h4>Contents</h4>
<p>
<input id="node_create" name="node_create" type="submit" value="Add" />
content
<input id="new_node_title" name="new_node_title" type="text" size="50" maxlength="100" value="<?php echo htmlspecialchars($new_node_title, ENT_COMPAT, 'UTF-8'); ?>" title="Title" onkeypress="return focusonenter(event, 'new_node_number')"/>
#
<input id="new_node_number" name="new_node_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($new_node_number, ENT_COMPAT, 'UTF-8'); ?>" title="Number" onkeypress="return submitonenter(event, 'node_create')"/>
</p>
<?php if ($thread_contents): ?>
<fieldset>
<legend>Summary</legend>
<table cellpadding="2" cellspacing="0">
<tbody>
<?php
$i=1;
$maxlen=strlen(count($thread_contents))+1;
foreach ($thread_contents as $c) {
	extract($c);	/* pos, node_title, node_url, node_number, node_ignored */
	$node_title = htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8');
	$node_url .= '?' . 'clang=' . $clang;
?>
<tr>
<td><input name="p[<?php echo $i; ?>]" type="text" size="2" maxlength="<?php echo $maxlen; ?>" value="<?php echo $pos; ?>" /></td>
<td class="aright"><a href="<?php echo $node_url; ?>"><?php echo $node_id; ?></a></td>
<td><a href="<?php echo $node_url; ?>"><?php echo $node_title; ?></a></td>
<?php if ($node_ignored): ?><td><img src="<?php echo $base_path; ?>/images/theme/edit/cross.png" alt="ignored" title="Ignored" /></td><?php endif; ?>
</tr>
<?php
	$i++;
}
?>
</tbody>
</table>
</fieldset>
<p>
<input id="thread_reorder" name="thread_reorder" type="submit" value="Sort" />
the list or
<input id="node_hide" name="node_hide" type="submit" value="Hide" />
or
<input id="node_show" name="node_show" type="submit" value="Show" />
or
<input id="node_delete" name="node_delete" type="submit" value="Delete" />
content #
<input id="old_node_number" name="old_node_number" type="text" size="2" maxlength="3" value="<?php echo htmlspecialchars($old_node_number, ENT_COMPAT, 'UTF-8'); ?>" title="Number" onkeypress="return submitonenter(event, 'node_delete')"/>
<?php if ($confirm_delete_node): ?>
<input id="node_confirmdelete" name="node_confirmdelete" type="submit" value="Confirm" />
<?php endif; ?>
</p>
<?php endif; ?>
</form>
<?php
$focus=false;
if ($missing_thread_title) {
	 $focus='#thread_title';
}
else if ($missing_thread_name or $bad_thread_name) {
	 $focus='#thread_name';
}
else if ($missing_new_node_title or $bad_new_node_title) {
	$focus='#new_node_title';
}
else if ($bad_new_node_number) {
	$focus='#new_node_number';
}
else if ($missing_old_node_number or $bad_old_node_number) {
	$focus='#old_node_number';
}
else if ($confirm_delete_node) {
	$focus='#old_node_number';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
