<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    2
 * @link       http://www.izend.org
 */

$aliases = array(
	array(
		'captcha'	=> 'captcha',
		'avatar'	=> 'avatar',
		'qrcode'	=> 'qrcode',
		'rss'		=> 'rssfeed',
	),
	'fr' => array(
		'accueil'	=> 'home',
		'contact'	=> 'contact',
		'utilisateur'	=> 'user',
		'déconnexion'	=> 'nobody',
		'compte'	=> 'account',
		'mot-de-passe'	=> 'password',
		'nouvel-utilisateur'	=> 'newuser',
		'recherche'	=> 'search',
		'suggestion'	=> 'suggest',
		'telechargement'	=> 'download',
		'page'	=> 'page',
		'edition'	=> 'editpage',
		'dossier'	=> 'folder',
		'edition/dossier'	=> 'folderedit',
		'article'	=> 'story',
		'edition/article'	=> 'storyedit',
		'manuel'	=> 'book',
		'edition/manuel'	=> 'bookedit',
		'fil'	=> 'thread',
		'edition/fil'	=> 'threadedit',
		'noeud'	=> 'node',
		'edition/noeud'	=> 'editnode',
	),
	'en' => array(
		'home'	=> 'home',
		'contact'	=> 'contact',
		'user'	=> 'user',
		'disconnect'	=> 'nobody',
		'password'	=> 'password',
		'account'	=> 'account',
		'new-user'	=> 'newuser',
		'search'	=> 'search',
		'suggest'	=> 'suggest',
		'download'	=> 'download',
		'page'	=> 'page',
		'edit'	=> 'editpage',
		'folder'	=> 'folder',
		'edit/folder'	=> 'folderedit',
		'article'	=> 'story',
		'edit/article'	=> 'storyedit',
		'manual'	=> 'book',
		'edit/manual'	=> 'bookedit',
		'thread'	=> 'thread',
		'edit/thread'	=> 'threadedit',
		'node'	=> 'node',
		'edit/node'	=> 'editnode',
	),
);

