<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    5
 * @link       http://www.izend.org
 */

global $strings;

$strings = array(
	array(
	),
	'en' => array(
		'description'			=> '',
		'keywords'				=> 'iZend',
		'http_bad_request:title'			=> 'Bad Request',
		'http_forbidden:title'				=> 'Forbidden',
		'http_internal_error:title'			=> 'Internal Error',
		'http_not_found:title'				=> 'Not Found',
		'http_not_implemented:title'		=> 'Not Implemented',
		'http_service_unavailable:title'	=> 'Service unavailable',
		'http_unauthorized:title'			=> 'Unauthorized',
		'install:title'			=> 'Installation',
		'home:title'			=> $sitename,
		'search:title'			=> 'Search',
		'contact:title'			=> 'Contact',
		'user:title'			=> 'Identification',
		'account:title'			=> 'Account',
		'newuser:title'			=> 'Registration',
		'password:title'		=> 'Password',
		'threadall:title'		=> 'Catalog',
		'bookall:title'			=> 'Manuals',
		'admin:title'			=> 'Gestion',
		'email:salutations'		=> 'See you soon.',
		'email:new_password_subject'	=> 'Your new password.',
		'email:new_password_text'		=> "Your new password is in the attached cryptogram.\n\nIf you didn't ask to change it, just ignore this message.\nNOTE: Your old password is still valid.\n\nIdentify yourself with the new password to activate it.",
		'email:new_user_subject'		=> 'Your account.',
		'email:new_user_text'			=> "Welcome!\n\nYour password is in the attached cryptogram.",
	),
	'fr' => array(
		'description'			=> '',
		'keywords'				=> 'iZend',
		'http_bad_request:title'			=> 'Mauvaise requête',
		'http_forbidden:title'				=> 'Interdit',
		'http_internal_error:title'			=> 'Erreur interne',
		'http_not_found:title'				=> 'Non trouvé',
		'http_not_implemented:title'		=> 'Non implémenté',
		'http_service_unavailable:title'	=> 'Service indisponible',
		'http_unauthorized:title'			=> 'Non autorisé',
		'install:title'			=> 'Installation',
		'home:title'			=> $sitename,
		'search:title'			=> 'Recherche',
		'user:title'			=> 'Identification',
		'contact:title'			=> 'Contact',
		'account:title'			=> 'Compte',
		'newuser:title'			=> 'Inscription',
		'password:title'		=> 'Mot de passe',
		'threadall:title'		=> 'Catalogue',
		'bookall:title'			=> 'Manuels',
		'admin:title'			=> 'Management',
		'email:salutations'		=> 'À bientôt.',
		'email:new_password_subject'	=> 'Votre mot de passe.',
		'email:new_password_text'		=> "Votre nouveau mot de passe est dans le cryptogramme en pièce jointe.\n\nSi vous n'avez pas demandé à en changer, veuillez ignorer ce message.\nNOTE : Votre ancien mot de passe est toujours valide.\n\nConnectez-vous avec le nouveau mot de passe pour l'activer.",
		'email:new_user_subject'		=> 'Votre compte.',
		'email:new_user_text'			=> "Bienvenue !\n\nVotre mot de passe est dans le cryptogramme en pièce jointe.",
	),
);

